/**
 * Pages « par revenu » : une entrée par montant, chacune autour d'un seuil qui lui est propre
 * (RECETTE §6.2). Les chiffres viennent du moteur, jamais écrits en dur.
 */
import { pension, asf, deduction, pensionImposable, impotBareme, tauxMarginal, MV, ASF, P } from './engine/pension';
import { formatMoney, formatPercent } from './format';
import type { FAQItem } from './seo';

export interface Angle { title: string; desc: string; h1: string; resume: string; h2a: string; pa: string; h2b: string; pb: string; faqs: FAQItem[] }
type L = 'fr' | 'en';
const m = (x: number, l: L) => formatMoney(x, 0, l);
const pc = (x: number, l: L, d = 1) => formatPercent(x, d, l);
const pk = (r: number, n: number, mode: 'reduit' | 'classique' | 'alterne' = 'classique') => pension(r, n, mode);
const Y = P.year;
const seuilReduit = Math.ceil(MV + ASF / P.bareme.taux['1'][0]);
const seuilClassique = Math.ceil(MV + ASF / P.bareme.taux['1'][1]);
const capMajeurMois = P.fiscalite.plafond_majeur / 12;

const FR: Record<number, () => Angle> = {
  1000: () => { const p = pk(1000, 1), a = asf(p.parEnfant, 1); return {
    title: `Pension alimentaire 1 000 € ${Y} : un montant sous l’ASF`, desc: `Pension alimentaire avec 1 000 € net en ${Y} : ${m(p.total, 'fr')} pour un enfant en droit classique, sous l’ASF. Ce que verse la CAF en complément, et pour 2 ou 3 enfants.`,
    h1: `Pension alimentaire avec 1 000 € net par mois : un montant que la CAF complète`,
    resume: `Avec 1 000 € de revenu net par mois, le parent qui verse ne dépasse le minimum vital de la table (${m(MV, 'fr')}) que de ${m(p.base, 'fr')}. La table du ministère de la Justice en tire une pension modeste : ${m(p.total, 'fr')} par mois pour un enfant en droit de visite classique, ${m(pk(1000, 1, 'reduit').total, 'fr')} en droit réduit. C’est bien en dessous de l’allocation de soutien familial, ${m(ASF, 'fr')} par enfant depuis le 1er avril ${Y}. Pour un parent qui élève seul l’enfant, la conséquence pratique est importante : la CAF verse la différence, ici ${m(a.parEnfant, 'fr')} par mois, au titre de l’ASF différentielle. À ce niveau de revenu, l’enjeu n’est donc pas tant le montant de la pension que sa fixation officielle, qui ouvre le droit au complément. Le simulateur ci-dessous donne le détail pour un à six enfants.`,
    h2a: 'Pourquoi la pension reste inférieure à l’ASF', pa: `La table soustrait d’abord le minimum vital, puis applique un taux par enfant au reste. Avec ${m(p.base, 'fr')} au-dessus du minimum vital, même le taux le plus élevé (droit réduit, un enfant) ne produit que ${m(pk(1000, 1, 'reduit').total, 'fr')}. Il faut ${m(seuilReduit, 'fr')} de revenu en droit réduit et ${m(seuilClassique, 'fr')} en droit classique pour que la pension d’un enfant atteigne l’ASF. Entre les deux, le parent isolé a intérêt à demander l’ASF différentielle, versée tous les trois mois, à condition que l’écart dépasse ${P.asf.seuil_non_versement} €.`,
    h2b: 'Ce que reçoit le parent qui élève l’enfant', pb: `Pour un enfant en droit classique : ${m(p.total, 'fr')} de pension, plus ${m(a.parEnfant, 'fr')} d’ASF différentielle, soit ${m(p.total + a.parEnfant, 'fr')} par mois, à condition de vivre seul. Avec deux enfants, la pension tombe à ${m(pk(1000, 2).parEnfant, 'fr')} par enfant et l’ASF complète chacun jusqu’à ${m(ASF, 'fr')}. Si le parent débiteur ne paie pas, l’ASF est versée à taux plein, à titre d’avance, et la CAF peut agir contre lui.`,
    faqs: [
      { q: 'Avec 1 000 € de salaire, doit-on payer une pension alimentaire ?', a: `Oui, la table du ministère de la Justice prévoit une pension dès que le revenu dépasse le minimum vital de ${m(MV, 'fr')}. Avec 1 000 € net, elle indique ${m(p.total, 'fr')} pour un enfant en droit classique et ${m(pk(1000, 2).total, 'fr')} pour deux enfants. Le juge peut retenir moins si les charges du parent, comme un loyer, rendent ce montant impossible à payer.` },
      { q: 'Le parent qui reçoit 47 € de pension peut-il toucher l’ASF ?', a: `Oui, s’il vit seul : la CAF verse l’ASF différentielle, c’est-à-dire la différence entre la pension fixée et ${m(ASF, 'fr')} par enfant, soit environ ${m(a.parEnfant, 'fr')} par mois ici. Elle est due chaque mois et versée tous les trois mois. Il faut que la pension ait été fixée par un jugement ou une convention, et que l’écart dépasse ${P.asf.seuil_non_versement} €.` },
      { q: 'Une pension si faible vaut-elle la peine d’être fixée par le juge ?', a: `Oui. Une fois fixée, même à ${m(p.total, 'fr')}, elle devient un titre recouvrable, revalorisé chaque année, qui ouvre droit à l’ASF différentielle et à l’intervention de l’Aripa en cas d’impayé, et elle pourra être révisée à la hausse si les revenus du parent débiteur augmentent.` },
    ] }; },
  1200: () => { const p1 = pk(1200, 1), p2 = pk(1200, 2); return {
    title: `Pension alimentaire 1 200 € ${Y} : cas du temps partiel`, desc: `Pension alimentaire avec 1 200 € net en ${Y} : ${m(p1.total, 'fr')} pour un enfant, ${m(p2.total, 'fr')} pour deux en droit classique. Le cas du temps partiel, ce qu’ajoute l’ASF de la CAF.`,
    h1: `Pension alimentaire avec 1 200 € net par mois : le cas du temps partiel`,
    resume: `Un revenu de 1 200 € net par mois correspond souvent à un temps partiel ou à un premier emploi. La table du ministère de la Justice laisse au parent qui verse son minimum vital de ${m(MV, 'fr')} et applique le taux au reste, ${m(p1.base, 'fr')}. Pour un enfant en droit de visite classique, la pension indicative est de ${m(p1.total, 'fr')} par mois ; pour deux enfants, de ${m(p2.total, 'fr')}, soit ${m(p2.parEnfant, 'fr')} chacun. Ces montants restent inférieurs à l’allocation de soutien familial (${m(ASF, 'fr')} par enfant), que la CAF peut verser en complément au parent qui élève seul les enfants. Le point de vigilance, à ce niveau, est le caractère durable du revenu : un temps partiel subi ou une reprise d’activité prévue sont des éléments que le juge peut prendre en compte, et qui justifieront une révision quand le revenu changera.`,
    h2a: 'Deux enfants : le taux baisse, mais l’ASF complète chaque enfant', pa: `Avec deux enfants, la table applique ${pc(p2.tauxEnfant, 'fr')} par enfant au lieu de ${pc(p1.tauxEnfant, 'fr')}, soit ${m(p2.parEnfant, 'fr')} chacun. Pour le parent isolé qui reçoit la pension, l’ASF différentielle se calcule enfant par enfant : ${m(asf(p2.parEnfant, 2).parEnfant, 'fr')} pour chacun, ${m(asf(p2.parEnfant, 2).total, 'fr')} au total. Au bout du compte, la CAF verse davantage que l’autre parent, situation fréquente sous ${m(seuilReduit, 'fr')} de revenu.`,
    h2b: 'Temps partiel : ce que le juge peut regarder', pb: `Le juge fixe la pension d’après les ressources réelles, mais il peut tenir compte de la capacité de gagner davantage quand un temps partiel est choisi plutôt que subi. Un parent qui passe à temps partiel juste avant l’audience devra l’expliquer. À l’inverse, un temps partiel imposé par l’employeur ou par la santé se documente facilement. Quand le revenu remontera, l’autre parent pourra demander une révision : à 1 800 €, la table donne ${m(pk(1800, 1).total, 'fr')} pour un enfant.`,
    faqs: [
      { q: 'Combien de pension pour deux enfants avec 1 200 € net ?', a: `La table du ministère de la Justice indique ${m(p2.total, 'fr')} par mois pour deux enfants en droit de visite classique, soit ${m(p2.parEnfant, 'fr')} par enfant. En droit réduit, ce serait ${m(pk(1200, 2, 'reduit').total, 'fr')} ; en résidence alternée, ${m(pk(1200, 2, 'alterne').total, 'fr')}. Ce sont des repères : le juge peut s’en écarter selon les charges et les besoins.` },
      { q: 'Un parent à temps partiel peut-il payer moins de pension ?', a: `La table s’applique au revenu réel : à 1 200 € net, elle donne ${m(p1.total, 'fr')} pour un enfant. Le juge peut toutefois considérer qu’un temps partiel choisi ne doit pas réduire la contribution, et retenir un revenu plus proche de ce que le parent pourrait gagner. Il faut donc expliquer et justifier pourquoi le temps de travail est réduit.` },
      { q: 'À 1 200 €, la pension compte-t-elle dans la déduction d’impôts ?', a: `Oui, elle est déductible pour un enfant mineur qui vit chez l’autre parent, mais l’avantage est faible : avec environ ${m(1200 * 12, 'fr')} de revenu imposable annuel sur une part, la tranche marginale est de ${pc(tauxMarginal(14400, 1), 'fr', 0)} et l’économie d’impôt sur ${m(p1.total * 12, 'fr')} de pension annuelle est d’environ ${m(deduction(p1.total * 12, 'mineur', 14400).economie, 'fr')}.` },
    ] }; },
  1500: () => { const p = pk(1500, 1), d = deduction(p.total * 12, 'mineur', 18000); return {
    title: `Pension alimentaire 1 500 € ${Y} : montant et impôt réel`, desc: `Pension alimentaire avec 1 500 € net en ${Y} : ${m(p.total, 'fr')} pour un enfant en droit classique, ${m(pk(1500, 2).total, 'fr')} pour deux. Le coût réel une fois la déduction d’impôt appliquée.`,
    h1: `Pension alimentaire avec 1 500 € net par mois : montant et coût réel`,
    resume: `À 1 500 € de revenu net mensuel, le parent qui verse dispose de ${m(p.base, 'fr')} au-dessus du minimum vital de la table. Pour un enfant en droit de visite classique, la pension indicative est de ${m(p.total, 'fr')} par mois, soit ${pc(p.total / 1500, 'fr')} du revenu ; pour deux enfants, ${m(pk(1500, 2).total, 'fr')}. Ce niveau de revenu illustre bien une idée reçue sur la fiscalité : la pension versée est déductible, mais dans la tranche à ${pc(tauxMarginal(18000, 1), 'fr', 0)}, l’économie reste limitée, environ ${m(d.economie, 'fr')} par an pour un enfant. Autrement dit, le coût réel de la pension est presque son montant affiché, à la différence d’un parent mieux payé. Pour le parent qui reçoit, la pension s’ajoute à son revenu imposable, après un abattement minimum de ${m(P.fiscalite.abattement_min_par_pensionne, 'fr')}. Le simulateur ci-dessous détaille les autres configurations.`,
    h2a: 'Une déduction qui rapporte peu à ce niveau de revenu', pa: `Avec environ ${m(18000, 'fr')} de revenu imposable sur une part, le parent débiteur est dans la tranche à ${pc(tauxMarginal(18000, 1), 'fr', 0)}. Déduire ${m(p.total * 12, 'fr')} de pension annuelle lui fait économiser environ ${m(d.economie, 'fr')} : le coût réel de la pension est de ${m(p.total * 12 - d.economie, 'fr')} sur l’année. Pour le même montant, un parent dans la tranche à 30 % économiserait près de trois fois plus. C’est un élément à garder en tête dans une négociation : un euro de pension ne coûte pas la même chose à tous.`,
    h2b: 'Et pour le parent qui reçoit la pension', pb: `La pension reçue est imposable : ${m(p.total * 12, 'fr')} par an, moins l’abattement de 10 % porté ici à son minimum de ${m(P.fiscalite.abattement_min_par_pensionne, 'fr')}, soit ${m(pensionImposable(p.total * 12).imposable, 'fr')} ajoutés au revenu imposable. Pour un parent isolé, avec la majoration de parts liée à l’enfant, l’effet sur l’impôt est souvent nul ou faible. La pension, ${m(p.parEnfant, 'fr')} par enfant, reste ici sous l’ASF : un parent isolé peut demander la différence à la CAF.`,
    faqs: [
      { q: 'Quelle pension pour un enfant avec 1 500 € de salaire net ?', a: `La table de référence du ministère de la Justice donne ${m(p.total, 'fr')} par mois en droit de visite classique, ${m(pk(1500, 1, 'reduit').total, 'fr')} en droit réduit et ${m(pk(1500, 1, 'alterne').total, 'fr')} en résidence alternée. Le calcul : (1 500 − ${m(MV, 'fr')}) × le taux de la colonne. Le juge reste libre d’adapter le montant aux besoins réels de l’enfant.` },
      { q: 'À 1 500 €, que coûte vraiment la pension après impôt ?', a: `Presque son montant affiché : dans la tranche à ${pc(tauxMarginal(18000, 1), 'fr', 0)}, la déduction de la pension réduit l’impôt d’environ ${m(d.economie, 'fr')} par an pour un enfant en droit classique, soit un coût réel de ${m(p.total * 12 - d.economie, 'fr')} sur l’année. Le calcul suppose une part de quotient familial, sans décote : un foyer différent obtiendra un chiffre un peu différent.` },
      { q: 'Avec 1 500 € et trois enfants, que donne la table ?', a: `Pour trois enfants en droit de visite classique, la table applique ${pc(pk(1500, 3).tauxEnfant, 'fr')} par enfant au revenu après minimum vital : ${m(pk(1500, 3).parEnfant, 'fr')} chacun, ${m(pk(1500, 3).total, 'fr')} au total. Il resterait au parent débiteur ${m(1500 - pk(1500, 3).total, 'fr')} pour se loger et vivre, ce que le juge examinera au regard de ses charges réelles.` },
    ] }; },
  1800: () => { const pr = pk(1800, 1, 'reduit'), pc_ = pk(1800, 1); return {
    title: `Pension alimentaire 1 800 € ${Y} : au seuil de l’ASF`, desc: `Pension alimentaire avec 1 800 € net en ${Y} : ${m(pc_.total, 'fr')} en droit classique, ${m(pr.total, 'fr')} en droit réduit, au-dessus de l’ASF dès ${m(seuilReduit, 'fr')} de revenu net. Le calcul.`,
    h1: `Pension alimentaire avec 1 800 € net par mois : le seuil où l’ASF s’efface`,
    resume: `À 1 800 € net par mois, la pension d’un enfant unique franchit un seuil discret mais concret. En droit de visite réduit, la table du ministère de la Justice donne ${m(pr.total, 'fr')} par mois : c’est un peu plus que l’allocation de soutien familial (${m(ASF, 'fr')}), qui ne peut donc plus compléter la pension. Le basculement se fait dès ${m(seuilReduit, 'fr')} de revenu. En droit de visite classique, en revanche, la pension reste à ${m(pc_.total, 'fr')}, encore sous l’ASF : un parent isolé peut toujours percevoir la différence, ${m(asf(pc_.parEnfant, 1).parEnfant, 'fr')} par mois. Le même revenu produit donc deux situations différentes pour le parent qui élève l’enfant, selon l’amplitude du droit de visite. C’est l’un des cas où la description exacte du rythme de visite pèse sur le budget. Le simulateur ci-dessous compare les trois colonnes.`,
    h2a: 'Droit réduit ou classique : le même revenu, deux budgets', pa: `En droit réduit, le parent qui reçoit la pension touche ${m(pr.total, 'fr')} et plus d’ASF. En droit classique, il touche ${m(pc_.total, 'fr')} de pension et ${m(asf(pc_.parEnfant, 1).parEnfant, 'fr')} d’ASF différentielle s’il vit seul, soit ${m(pc_.total + asf(pc_.parEnfant, 1).parEnfant, 'fr')}. Paradoxalement, le droit classique lui laisse un peu plus au total, parce que la CAF complète. Ce n’est vrai que tant que la pension classique reste sous l’ASF, c’est-à-dire jusqu’à ${m(seuilClassique, 'fr')} de revenu du débiteur.`,
    h2b: 'Deux enfants à 1 800 €', pb: `Avec deux enfants, le taux par enfant baisse et la pension de chacun redescend sous l’ASF même en droit réduit : ${m(pk(1800, 2, 'reduit').parEnfant, 'fr')} par enfant, ${m(pk(1800, 2).parEnfant, 'fr')} en droit classique. Le seuil de l’ASF se situe donc bien plus haut pour une fratrie. Le parent débiteur, lui, verse ${m(pk(1800, 2).total, 'fr')} en droit classique et peut déduire cette somme de son revenu imposable.`,
    faqs: [
      { q: 'À partir de quel revenu la pension dépasse-t-elle l’ASF ?', a: `Pour un enfant unique, à partir de ${m(seuilReduit, 'fr')} de revenu net du parent débiteur en droit de visite réduit, et de ${m(seuilClassique, 'fr')} en droit classique, avec le minimum vital de ${m(MV, 'fr')} et l’ASF de ${m(ASF, 'fr')}. Sous ces seuils, le parent isolé qui reçoit la pension peut demander l’ASF différentielle à la CAF.` },
      { q: 'Avec 1 800 €, combien pour un enfant en droit de visite réduit ?', a: `La table indique ${m(pr.total, 'fr')} par mois : (1 800 − ${m(MV, 'fr')}) × ${pc(pr.tauxEnfant, 'fr')}. Le droit réduit correspond, selon justice.fr, à un droit de visite plus restreint que le week-end sur deux, par exemple une journée ou des visites en lieu médiatisé, où le parent débiteur assume peu de frais directs.` },
      { q: 'Le parent qui reçoit perd-il l’ASF si la pension augmente ?', a: `L’ASF différentielle diminue à mesure que la pension augmente, et disparaît quand elle atteint ${m(ASF, 'fr')} par enfant ; si l’écart est inférieur à ${P.asf.seuil_non_versement} €, rien n’est versé. Une révision à la hausse de la pension n’augmente donc pas toujours le total reçu par le parent isolé, tant que la pension reste sous l’ASF.` },
    ] }; },
  2000: () => { const p = pk(2000, 2); return {
    title: `Pension alimentaire 2 000 € ${Y} : la ligne officielle`, desc: `Pension alimentaire avec 2 000 € net en ${Y} : ${m(pk(2000, 1).total, 'fr')} pour un enfant, ${m(p.total, 'fr')} pour deux en droit classique, ligne vérifiée au centime sur la table justice.fr.`,
    h1: `Pension alimentaire avec 2 000 € net par mois : la ligne de la table, vérifiée`,
    resume: `Le revenu de 2 000 € net par mois sert souvent d’exemple, et c’est l’une des lignes de la table du ministère de la Justice que notre moteur rejoue à chaque publication. Après le minimum vital de ${m(MV, 'fr')}, il reste ${m(p.base, 'fr')} sur lesquels s’appliquent les taux. Pour un enfant en droit de visite classique, la pension indicative est de ${m(pk(2000, 1).total, 'fr')} par mois ; pour deux enfants, ${m(p.parEnfant, 'fr')} chacun, soit ${m(p.total, 'fr')} ; pour trois, ${m(pk(2000, 3).total, 'fr')}. Ces chiffres sont identiques, au centime près, à ceux publiés par justice.fr pour cette ligne, ce que vérifie un test automatique. La pension d’un enfant unique en droit classique reste juste sous l’ASF de ${m(ASF, 'fr')}, qui s’efface à partir de ${m(seuilClassique, 'fr')}. Le simulateur ci-dessous donne les dix-huit cases de la ligne.`,
    h2a: 'La ligne 2 000 € de la table, case par case', pa: `La table publie, pour chaque revenu, dix-huit montants par enfant : un à six enfants, trois amplitudes de droit de visite. Pour 2 000 €, ils vont de ${m(pk(2000, 1, 'reduit').parEnfant, 'fr')} (un enfant, droit réduit) à ${m(pk(2000, 6, 'alterne').parEnfant, 'fr')} (six enfants, résidence alternée). Notre test compare ces dix-huit valeurs au centime avec celles de justice.fr : si l’une change, la mise en ligne est bloquée jusqu’à vérification.`,
    h2b: 'Deux enfants à 2 000 € : ce que reçoit chaque foyer', pb: `Le parent débiteur verse ${m(p.total, 'fr')} par mois, soit ${m(p.total * 12, 'fr')} par an, déductibles de son revenu : avec environ ${m(24000, 'fr')} de revenu imposable sur une part, l’économie d’impôt est d’environ ${m(deduction(p.total * 12, 'mineur', 24000).economie, 'fr')}. Le parent qui reçoit déclare ${m(pensionImposable(p.total * 12).imposable, 'fr')} après abattement. Chaque pension par enfant, ${m(p.parEnfant, 'fr')}, reste sous l’ASF : un parent isolé peut demander le complément.`,
    faqs: [
      { q: 'Combien de pension alimentaire avec 2 000 € net et deux enfants ?', a: `La table du ministère de la Justice indique ${m(p.parEnfant, 'fr')} par enfant en droit de visite classique, soit ${m(p.total, 'fr')} par mois pour les deux. En droit réduit, ${m(pk(2000, 2, 'reduit').total, 'fr')} ; en résidence alternée, ${m(pk(2000, 2, 'alterne').total, 'fr')}. Ces montants sont ceux publiés par justice.fr pour un revenu de 2 000 €.` },
      { q: 'Comment vérifier soi-même le calcul de la table à 2 000 € ?', a: `Retirez le minimum vital : 2 000 − ${m(MV, 'fr')} = ${m(p.base, 'fr')}. Multipliez par le taux par enfant de votre colonne, par exemple ${pc(p.tauxEnfant, 'fr')} pour deux enfants en droit classique : ${m(p.parEnfant, 'fr')}. Multipliez enfin par le nombre d’enfants : ${m(p.total, 'fr')}. Le résultat doit correspondre à la case de la table publiée sur justice.fr.` },
      { q: 'À 2 000 €, la pension d’un enfant unique dépasse-t-elle l’ASF ?', a: `En droit classique, non : ${m(pk(2000, 1).total, 'fr')}, juste sous l’ASF de ${m(ASF, 'fr')}, ce qui laisse une ASF différentielle d’environ ${m(asf(pk(2000, 1).parEnfant, 1).parEnfant, 'fr')} au parent isolé. En droit réduit, oui : ${m(pk(2000, 1, 'reduit').total, 'fr')}. La bascule en droit classique se fait à ${m(seuilClassique, 'fr')} de revenu.` },
    ] }; },
  2200: () => { const p = pk(2200, 1); return {
    title: `Pension alimentaire 2 200 € ${Y} : plus d’ASF en classique`, desc: `Pension alimentaire avec 2 200 € net en ${Y} : ${m(p.total, 'fr')} pour un enfant en droit classique, au-dessus de l’ASF : le complément CAF s’arrête. 2 et 3 enfants.`,
    h1: `Pension alimentaire avec 2 200 € net par mois : la fin du complément de la CAF`,
    resume: `À 2 200 € de revenu net, la pension d’un enfant unique en droit de visite classique atteint ${m(p.total, 'fr')} par mois selon la table du ministère de la Justice. C’est le premier revenu de nos pages où elle dépasse l’allocation de soutien familial (${m(ASF, 'fr')}) dans la colonne la plus courante : le seuil exact est de ${m(seuilClassique, 'fr')}. Concrètement, le parent isolé qui reçoit la pension ne peut plus prétendre à l’ASF différentielle, sauf si la pension n’est pas payée, auquel cas l’ASF reste versée à titre d’avance. Pour deux enfants, la pension est de ${m(pk(2200, 2).parEnfant, 'fr')} par enfant, encore sous l’ASF ; la fratrie garde donc le complément. Ce revenu correspond aussi à celui pour lequel les simulateurs officiels et le nôtre donnent le même chiffre, mais seul le nôtre affiche l’effet sur l’ASF et l’impôt. Le simulateur ci-dessous fait la comparaison.`,
    h2a: 'Au-delà du seuil, l’ASF ne joue plus que comme avance', pa: `Tant que la pension est payée, un parent isolé dont l’enfant reçoit ${m(p.total, 'fr')} n’a plus droit à l’ASF différentielle. Si le parent débiteur cesse de payer, en revanche, l’ASF redevient pleine, ${m(ASF, 'fr')} par enfant, versée à titre d’avance pendant que la CAF ou l’Aripa recouvre la pension. Elle ne couvre alors qu’une partie de la pension due, le reste étant poursuivi auprès du débiteur.`,
    h2b: 'Un enfant, deux enfants : où se situe le seuil', pb: `Pour deux enfants en droit classique, la pension par enfant ne dépasse l’ASF qu’à partir de ${m(Math.ceil(MV + ASF / P.bareme.taux['2'][1]), 'fr')} de revenu ; pour trois, à partir de ${m(Math.ceil(MV + ASF / P.bareme.taux['3'][1]), 'fr')}. À 2 200 €, une fratrie de deux reçoit ${m(pk(2200, 2).total, 'fr')} de pension, et un parent isolé peut demander ${m(asf(pk(2200, 2).parEnfant, 2).total, 'fr')} d’ASF différentielle en plus.`,
    faqs: [
      { q: 'Avec 2 200 € net, combien pour un enfant ?', a: `${m(p.total, 'fr')} par mois en droit de visite classique, ${m(pk(2200, 1, 'reduit').total, 'fr')} en droit réduit et ${m(pk(2200, 1, 'alterne').total, 'fr')} en résidence alternée, selon la table du ministère de la Justice. Le calcul retire le minimum vital de ${m(MV, 'fr')} puis applique le taux de la colonne au reste, ${m(p.base, 'fr')}.` },
      { q: 'Pourquoi le parent isolé perd-il l’ASF quand la pension dépasse 200 € ?', a: `Parce que l’ASF différentielle complète une pension jusqu’à ${m(ASF, 'fr')} par enfant : une fois ce montant dépassé, il n’y a plus rien à compléter. L’ASF reste en revanche versée à taux plein, à titre d’avance, si la pension fixée n’est pas payée, la CAF se chargeant ensuite de la récupérer auprès de l’autre parent.` },
      { q: 'À 2 200 €, la pension pour deux enfants dépasse-t-elle l’ASF ?', a: `Non : ${m(pk(2200, 2).parEnfant, 'fr')} par enfant en droit classique, sous les ${m(ASF, 'fr')} de l’ASF. Un parent isolé peut donc demander l’ASF différentielle pour chacun des deux enfants, environ ${m(asf(pk(2200, 2).parEnfant, 2).parEnfant, 'fr')} par enfant et par mois, versée tous les trois mois par la CAF.` },
    ] }; },
  2500: () => { const p = pk(2500, 1), d = deduction(p.total * 12, 'mineur', 30000); return {
    title: `Pension alimentaire 2 500 € ${Y} : la tranche à 30 %`, desc: `Pension alimentaire avec 2 500 € net en ${Y} : ${m(p.total, 'fr')} pour un enfant en droit classique. Entrée dans la tranche d’impôt à 30 % : ce que la déduction fait gagner.`,
    h1: `Pension alimentaire avec 2 500 € net par mois : la tranche à 30 % change le coût`,
    resume: `À 2 500 € net par mois, soit environ ${m(30000, 'fr')} de revenu imposable annuel, le parent qui verse la pension passe dans la tranche d’impôt à ${pc(tauxMarginal(30000, 1), 'fr', 0)} s’il est seul à déclarer. Ce détail fiscal change le coût réel de la pension. La table du ministère de la Justice donne ${m(p.total, 'fr')} par mois pour un enfant en droit de visite classique, ${m(pk(2500, 2).total, 'fr')} pour deux. Déduite du revenu, la pension d’un enfant fait économiser environ ${m(d.economie, 'fr')} d’impôt sur l’année : son coût réel tombe à ${m(p.total * 12 - d.economie, 'fr')}, soit ${m((p.total * 12 - d.economie) / 12, 'fr')} par mois. Au-delà de ce revenu, chaque euro de pension supplémentaire est en partie financé par l’impôt évité. C’est un argument concret dans une négociation entre parents. Le simulateur ci-dessous affiche ce coût réel.`,
    h2a: 'Le passage dans la tranche à 30 %', pa: `Le barème des revenus ${P.fiscalite.revenus} fait passer de 11 % à 30 % au-delà de ${m(P.fiscalite.tranches[1].jusqua!, 'fr')} de revenu imposable par part. Un parent seul à ${m(30000, 'fr')} est juste au-dessus : la pension déduite sort d’abord de la tranche à 30 %, puis de celle à 11 %. Plus la pension est élevée, plus la part déduite à 11 % augmente, si bien que l’économie moyenne reste entre les deux taux.`,
    h2b: 'Avec deux enfants à 2 500 €', pb: `Pour deux enfants en droit classique, la pension atteint ${m(pk(2500, 2).total, 'fr')} par mois, ${m(pk(2500, 2).total * 12, 'fr')} par an. L’économie d’impôt estimée est d’environ ${m(deduction(pk(2500, 2).total * 12, 'mineur', 30000).economie, 'fr')}. Le parent qui reçoit déclare ${m(pensionImposable(pk(2500, 2).total * 12).imposable, 'fr')} après abattement. Chaque pension par enfant, ${m(pk(2500, 2).parEnfant, 'fr')}, se situe encore sous l’ASF : un parent isolé peut demander le complément.`,
    faqs: [
      { q: 'Quelle pension pour un enfant avec 2 500 € de salaire ?', a: `La table du ministère de la Justice indique ${m(p.total, 'fr')} par mois en droit de visite classique, ${m(pk(2500, 1, 'reduit').total, 'fr')} en droit réduit et ${m(pk(2500, 1, 'alterne').total, 'fr')} en résidence alternée. Le calcul part de 2 500 € moins le minimum vital de ${m(MV, 'fr')}, soit ${m(p.base, 'fr')}, multiplié par le taux de la colonne.` },
      { q: 'Combien rapporte la déduction de la pension à 2 500 € net ?', a: `Environ ${m(d.economie, 'fr')} par an pour un enfant en droit classique, avec une part de quotient familial et un revenu imposable d’environ ${m(30000, 'fr')}, sans décote. Le coût réel de la pension est alors de ${m(p.total * 12 - d.economie, 'fr')} sur l’année au lieu de ${m(p.total * 12, 'fr')}. En résidence alternée, il n’y a pas de déduction possible.` },
      { q: 'À 2 500 €, vaut-il mieux une résidence alternée ?', a: `Le choix de la résidence se fait dans l’intérêt de l’enfant, pas pour le montant. Côté chiffres, la table donne ${m(pk(2500, 1, 'alterne').total, 'fr')} en alternance contre ${m(p.total, 'fr')} en droit classique, mais le parent assume alors directement la moitié des dépenses courantes de l’enfant et perd la déduction fiscale de la pension. L’écart réel est donc bien plus faible qu’il n’y paraît.` },
    ] }; },
  3000: () => { const pa = pk(3000, 1, 'alterne'), pcl = pk(3000, 1); return {
    title: `Pension alimentaire 3 000 € ${Y} : alternance ou classique`, desc: `Pension alimentaire avec 3 000 € net en ${Y} : ${m(pcl.total, 'fr')} pour un enfant en droit classique, ${m(pa.total, 'fr')} en résidence alternée. Qui paie quand les revenus diffèrent.`,
    h1: `Pension alimentaire avec 3 000 € net par mois : résidence alternée ou classique`,
    resume: `À 3 000 € net par mois, la question de la résidence alternée se pose souvent, et avec elle celle d’une pension entre parents aux revenus inégaux. La table du ministère de la Justice donne ${m(pcl.total, 'fr')} par mois pour un enfant en droit de visite classique, mais ${m(pa.total, 'fr')} en résidence alternée, où chaque parent assume déjà la moitié du temps de vie de l’enfant. Pour deux enfants, les montants sont de ${m(pk(3000, 2).total, 'fr')} et ${m(pk(3000, 2, 'alterne').total, 'fr')}. En alternance, une pension n’est pas automatique : elle se justifie quand l’autre parent gagne nettement moins, et c’est le parent le plus aisé qui la verse. La table ne regarde pourtant que le revenu du débiteur : face à un autre parent qui gagne ${m(2800, 'fr')}, le juge peut ne fixer aucune pension. Le simulateur compare les colonnes.`,
    h2a: 'En résidence alternée, l’écart de revenus décide', pa: `La table lit le revenu d’un seul parent. En alternance, ce n’est pas suffisant : deux parents à ${m(3000, 'fr')} et ${m(2900, 'fr')} n’ont aucune raison de se verser une pension, alors que la colonne alternée afficherait ${m(pa.total, 'fr')}. Le juge, ou les parents dans leur convention, regardent donc l’écart. Une pratique courante est de fixer une pension faible et un partage des frais exceptionnels au prorata des revenus, plus simple à suivre qu’un montant mensuel élevé.`,
    h2b: 'Ce que chaque formule implique au-delà du montant', pb: `En droit classique, la pension de ${m(pcl.total, 'fr')} est déductible pour le parent qui la verse (économie estimée : ${m(deduction(pcl.total * 12, 'mineur', 36000).economie, 'fr')} par an sur une part) et imposable pour l’autre. En alternance, elle n’est pas déductible, car chaque parent compte l’enfant dans ses parts. Le choix de la résidence se fait d’abord dans l’intérêt de l’enfant ; ces chiffres servent seulement à mesurer ce qu’il change aux deux budgets.`,
    faqs: [
      { q: 'Avec 3 000 € net, combien de pension en garde alternée ?', a: `La colonne « alterné » de la table du ministère de la Justice donne ${m(pa.total, 'fr')} par mois pour un enfant et ${m(pk(3000, 2, 'alterne').total, 'fr')} pour deux. Ce montant n’est pertinent que si l’autre parent gagne nettement moins : en résidence alternée, elle n’est due qu’au parent qui n’a pas des revenus suffisants pour les besoins de l’enfant quand il est chez lui.` },
      { q: 'À 3 000 €, combien pour un enfant en droit de visite classique ?', a: `${m(pcl.total, 'fr')} par mois selon la table : (3 000 − ${m(MV, 'fr')}) × ${pc(pcl.tauxEnfant, 'fr')}. En droit réduit, ce serait ${m(pk(3000, 1, 'reduit').total, 'fr')}. La pension est déductible pour le parent qui la verse, ce qui ramène son coût réel autour de ${m(pcl.total * 12 - deduction(pcl.total * 12, 'mineur', 36000).economie, 'fr')} par an.` },
      { q: 'En alternance, peut-on remplacer la pension par un partage des frais ?', a: `Oui, si les deux parents sont d’accord et l’écrivent dans une convention, ou si le juge le décide : la pension peut prendre la forme d’une prise en charge directe de certains frais de l’enfant, totale ou partielle. Service-public.fr cite par exemple le partage par moitié des frais de scolarité. La clause doit lister les frais et la clé de partage.` },
    ] }; },
  3500: () => { const p = pk(3500, 3); return {
    title: `Pension alimentaire 3 500 € ${Y} : le cas de 3 enfants`, desc: `Pension alimentaire avec 3 500 € net en ${Y} : ${m(p.total, 'fr')} pour trois enfants en droit classique, ce qui reste au parent qui verse et ce que le juge peut ajuster.`,
    h1: `Pension alimentaire avec 3 500 € net par mois : trois enfants et le reste à vivre`,
    resume: `Avec 3 500 € de revenu net et trois enfants, la pension devient l’un des premiers postes du budget du parent qui verse. La table du ministère de la Justice applique ${pc(p.tauxEnfant, 'fr')} par enfant au revenu après minimum vital, soit ${m(p.parEnfant, 'fr')} par enfant et ${m(p.total, 'fr')} par mois pour les trois en droit de visite classique, ${pc(p.total / 3500, 'fr')} du revenu total. Il reste ${m(3500 - p.total, 'fr')} pour le logement, les trajets pour voir les enfants et la vie courante. C’est à ce niveau que le reste à vivre devient l’argument central devant le juge : un loyer de ${m(1000, 'fr')} ne laisse plus que ${m(3500 - p.total - 1000, 'fr')}. Inversement, la déduction de la pension, sans plafond pour des enfants mineurs, allège nettement l’impôt. Le simulateur ci-dessous donne les autres configurations.`,
    h2a: 'Le reste à vivre, avec et sans loyer', pa: `Le minimum vital de la table, ${m(MV, 'fr')}, ne tient pas compte du logement. Avec trois enfants à 3 500 €, le parent débiteur garde ${m(3500 - p.total, 'fr')} avant de se loger. S’il est propriétaire sans crédit, la marge reste confortable ; s’il paie un loyer de ${m(1000, 'fr')} en ville, il lui reste ${m(3500 - p.total - 1000, 'fr')}, et il doit accueillir les enfants un week-end sur deux. Le juge peut retenir moins que la table si ces charges sont justifiées.`,
    h2b: 'L’effet de la déduction fiscale', pb: `Les ${m(p.total * 12, 'fr')} de pension annuelle sont déductibles en totalité pour des enfants mineurs qui vivent chez l’autre parent. Avec environ ${m(42000, 'fr')} de revenu imposable sur une part, l’économie d’impôt estimée est de ${m(deduction(p.total * 12, 'mineur', 42000).economie, 'fr')} sur l’année, soit ${m(deduction(p.total * 12, 'mineur', 42000).economie / 12, 'fr')} par mois. Le coût réel des trois pensions descend à ${m(p.total - deduction(p.total * 12, 'mineur', 42000).economie / 12, 'fr')} par mois.`,
    faqs: [
      { q: 'Combien de pension pour trois enfants avec 3 500 € net ?', a: `La table du ministère de la Justice indique ${m(p.total, 'fr')} par mois en droit de visite classique, soit ${m(p.parEnfant, 'fr')} par enfant. En droit réduit, ce serait ${m(pk(3500, 3, 'reduit').total, 'fr')} ; en résidence alternée, ${m(pk(3500, 3, 'alterne').total, 'fr')}. Le juge peut adapter ces montants aux charges du parent et aux besoins de chaque enfant.` },
      { q: 'À 3 500 €, que reste-t-il au parent après la pension de trois enfants ?', a: `${m(3500 - p.total, 'fr')} par mois avant toute charge de logement, puisque la table prélève ${m(p.total, 'fr')}. Après un loyer de ${m(1000, 'fr')}, il resterait ${m(3500 - p.total - 1000, 'fr')}. C’est ce reste à vivre, documenté par le bail et les quittances, que le parent débiteur peut présenter au juge pour obtenir un montant inférieur à la table.` },
      { q: 'La pension de trois enfants est-elle entièrement déductible ?', a: `Oui, pour des enfants mineurs qui ont leur résidence principale chez l’autre parent et ne comptent pas dans le quotient familial du parent qui verse : la déduction n’est pas plafonnée. Avec ${m(p.total * 12, 'fr')} de pension annuelle et environ ${m(42000, 'fr')} de revenu imposable sur une part, l’économie estimée est de ${m(deduction(p.total * 12, 'mineur', 42000).economie, 'fr')}.` },
    ] }; },
  4000: () => { const a = pk(3000, 1), b = pk(4000, 1); return {
    title: `Pension alimentaire 4 000 € ${Y} : révision après une hausse`, desc: `Pension alimentaire avec 4 000 € net en ${Y} : ${m(b.total, 'fr')} pour un enfant en droit classique. Révision à la hausse quand le salaire augmente : écart chiffré, preuves.`,
    h1: `Pension alimentaire avec 4 000 € net par mois : quand le salaire a augmenté`,
    resume: `Un revenu de 4 000 € net arrive souvent après une promotion ou un changement d’emploi, et pose une question précise : le parent qui reçoit la pension peut-il demander davantage ? Oui, si la hausse est un élément nouveau depuis la dernière décision ; elle fait partie des motifs de révision admis. Selon la table du ministère de la Justice, un parent qui versait ${m(a.total, 'fr')} pour un enfant en droit classique quand il gagnait ${m(3000, 'fr')} verserait ${m(b.total, 'fr')} à 4 000 €, soit ${m(b.total - a.total, 'fr')} de plus par mois. Pour deux enfants, la pension passe de ${m(pk(3000, 2).total, 'fr')} à ${m(pk(4000, 2).total, 'fr')}. La révision n’est pas automatique : il faut un accord homologué ou une décision du juge, et la preuve des nouveaux revenus. Le simulateur ci-dessous donne les montants à 4 000 €.`,
    h2a: 'Demander une révision à la hausse', pa: `Le parent créancier doit montrer que les ressources de l’autre parent ont augmenté depuis la dernière décision. L’avis d’impôt, s’il peut l’obtenir, ou tout élément sur le nouveau poste, sert de preuve. Il saisit le juge aux affaires familiales, sans avocat obligatoire, avec le formulaire de demande et un calcul de la table aux deux revenus. Le juge apprécie aussi les besoins de l’enfant, qui ont souvent augmenté entre-temps.`,
    h2b: 'À 4 000 €, la pension et l’impôt', pb: `À 4 000 € net, soit environ ${m(48000, 'fr')} de revenu imposable, le parent débiteur est dans la tranche à ${pc(tauxMarginal(48000, 1), 'fr', 0)}. La déduction de ${m(b.total * 12, 'fr')} de pension annuelle pour un enfant mineur lui fait économiser environ ${m(deduction(b.total * 12, 'mineur', 48000).economie, 'fr')}. La hausse de pension de ${m(b.total - a.total, 'fr')} par mois ne lui coûte donc réellement qu’environ ${m((b.total - a.total) * 0.7, 'fr')}.`,
    faqs: [
      { q: 'Combien de pension pour un enfant avec 4 000 € de salaire net ?', a: `La table du ministère de la Justice indique ${m(b.total, 'fr')} par mois en droit de visite classique, ${m(pk(4000, 1, 'reduit').total, 'fr')} en droit réduit et ${m(pk(4000, 1, 'alterne').total, 'fr')} en résidence alternée. Le calcul : (4 000 − ${m(MV, 'fr')}) × le taux par enfant de la colonne. Le juge peut adapter selon les besoins et les charges.` },
      { q: 'L’autre parent a été augmenté : la pension augmente-t-elle seule ?', a: 'Non. Seule la revalorisation annuelle sur l’indice des prix s’applique sans juge. Une hausse liée aux revenus suppose une révision : un nouvel accord homologué ou une décision du juge aux affaires familiales, saisi par le parent qui reçoit la pension avec la preuve de l’augmentation. Le nouveau montant s’applique à partir de la date fixée par le juge.' },
      { q: 'Peut-on demander une révision si l’on ne connaît pas le nouveau salaire ?', a: `Oui. Le parent qui demande la révision présente ce qu’il sait (nouveau poste, train de vie) et chiffre les besoins de l’enfant. Si les revenus de l’autre parent ne sont pas connus, le juge peut fixer la pension au montant demandé, ou le réduire s’il le juge disproportionné. À l’audience, chaque parent doit produire ses justificatifs de revenus.` },
    ] }; },
  5000: () => { const p = pk(5000, 1); return {
    title: `Pension alimentaire 5 000 € ${Y} : enfant majeur, plafond`, desc: `Pension alimentaire avec 5 000 € net en ${Y} : ${m(p.total, 'fr')} pour un enfant. Après 18 ans, la déduction plafonnée à 6 855 € par an ne couvre plus toute la pension.`,
    h1: `Pension alimentaire avec 5 000 € net par mois : quand l’enfant devient majeur`,
    resume: `À 5 000 € net par mois, la pension d’un enfant unique en droit de visite classique atteint ${m(p.total, 'fr')} selon la table du ministère de la Justice, soit ${m(p.total * 12, 'fr')} par an. Tant que l’enfant est mineur, elle est déductible en totalité pour le parent qui la verse. Mais à sa majorité, si l’enfant n’est plus rattaché et vit à part, la déduction est plafonnée à ${m(P.fiscalite.plafond_majeur, 'fr')} par an et par enfant, soit ${m(capMajeurMois, 'fr')} par mois. La pension de la table dépasse ce plafond dès ${m(Math.ceil(MV + capMajeurMois / P.bareme.taux['1'][1]), 'fr')} de revenu en droit classique : à 5 000 €, ${m(p.total * 12 - P.fiscalite.plafond_majeur, 'fr')} par an ne sont plus déductibles, et l’enfant, de son côté, ne déclare que la part déduite. La pension, elle, continue tant que l’enfant n’est pas autonome. Le simulateur ci-dessous donne les montants à 5 000 €.`,
    h2a: 'Le plafond de déduction pour un enfant majeur', pa: `Pour les revenus ${P.fiscalite.revenus}, la pension versée à un enfant majeur non rattaché est déductible dans la limite de ${m(P.fiscalite.plafond_majeur, 'fr')} par an. À 5 000 € de revenu, la pension de la table pour un enfant (${m(p.total * 12, 'fr')} par an) dépasse ce plafond. Le parent a alors un choix : déduire la pension plafonnée, ou rattacher l’enfant à son foyer fiscal, ce qui exclut la déduction. Le bon choix dépend de sa tranche marginale et des revenus du jeune.`,
    h2b: 'Revenus élevés : la forme de la pension compte', pb: `Avec des revenus élevés, la pension prend souvent une forme mixte : un montant mensuel plus la prise en charge directe de certains frais, comme les études supérieures ou un logement étudiant, ce que prévoit service-public.fr. Pour un enfant majeur, payer directement le loyer d’un studio et verser un complément plus faible peut être plus clair pour tout le monde ; les deux sont déductibles ensemble, dans la limite du plafond.`,
    faqs: [
      { q: 'Avec 5 000 € net, combien de pension pour un enfant ?', a: `La table du ministère de la Justice indique ${m(p.total, 'fr')} par mois en droit de visite classique, ${m(pk(5000, 1, 'reduit').total, 'fr')} en droit réduit et ${m(pk(5000, 1, 'alterne').total, 'fr')} en résidence alternée. Pour deux enfants en droit classique, ${m(pk(5000, 2).total, 'fr')}. Le juge peut s’écarter de la table selon les besoins réels de l’enfant et le train de vie de la famille.` },
      { q: 'À 5 000 €, quelle part de la pension d’un enfant majeur est déductible ?', a: `Au plus ${m(P.fiscalite.plafond_majeur, 'fr')} par an pour un enfant majeur non rattaché qui vit à part, sur les revenus ${P.fiscalite.revenus}. Avec une pension de ${m(p.total * 12, 'fr')} par an, ${m(p.total * 12 - P.fiscalite.plafond_majeur, 'fr')} ne sont pas déductibles. L’enfant déclare de son côté le montant déduit, avec un abattement de 10 %.` },
      { q: 'Vaut-il mieux rattacher l’enfant majeur ou déduire la pension ?', a: 'Les deux options s’excluent : un enfant rattaché donne une demi-part supplémentaire, ou plus, au foyer du parent, mais celui-ci ne peut plus déduire de pension pour lui. Le rattachement est souvent plus intéressant pour un parent modestement imposé, la déduction pour un parent dans une tranche élevée. Le simulateur officiel des impôts permet de comparer précisément.' },
    ] }; },
  6000: () => { const p = pk(6000, 1); return {
    title: `Pension alimentaire 6 000 € ${Y} : la part du revenu grimpe`, desc: `Pension alimentaire avec 6 000 € net en ${Y} : ${m(p.total, 'fr')} pour un enfant, ${m(pk(6000, 2).total, 'fr')} pour deux. Plus le revenu monte, plus la pension se rapproche du taux brut.`,
    h1: `Pension alimentaire avec 6 000 € net par mois : la table aux revenus élevés`,
    resume: `À 6 000 € de revenu net mensuel, la table du ministère de la Justice donne ${m(p.total, 'fr')} par mois pour un enfant en droit de visite classique, ${m(pk(6000, 2).total, 'fr')} pour deux et ${m(pk(6000, 3).total, 'fr')} pour trois. À ce niveau, un effet mathématique de la table devient visible : le minimum vital de ${m(MV, 'fr')} pèse de moins en moins, si bien que la pension représente une part du revenu de plus en plus proche du taux de la colonne. Pour un enfant en droit classique, elle atteint ${pc(p.total / 6000, 'fr')} du revenu total, contre un taux de ${pc(p.tauxEnfant, 'fr')} ; à 1 500 €, elle n’en représentait que ${pc(pk(1500, 1).total / 1500, 'fr')}. Le juge peut toutefois s’écarter de la table pour les hauts revenus, en fonction des besoins réels de l’enfant et du train de vie. Le simulateur ci-dessous donne le détail.`,
    h2a: 'Pourquoi la part du revenu augmente avec le revenu', pa: `La table applique un taux au revenu diminué d’un montant fixe. Ce montant fixe représente ${pc(MV / 1500, 'fr', 0)} d’un revenu de 1 500 €, mais seulement ${pc(MV / 6000, 'fr', 0)} d’un revenu de 6 000 €. La pension, en part du revenu total, se rapproche donc du taux brut quand le revenu monte. Le tableau ci-dessous le montre pour un enfant en droit classique.`,
    h2b: 'Hauts revenus : besoins de l’enfant et train de vie', pb: `La table n’a pas de plafond, mais le juge fixe la pension selon les besoins de l’enfant, qui ne croissent pas indéfiniment avec le revenu du parent. Il tient compte du train de vie que l’enfant avait avant la séparation, de sa scolarité, de ses activités. Pour un enfant majeur, la déduction fiscale est plafonnée à ${m(P.fiscalite.plafond_majeur, 'fr')} par an, nettement sous la pension de la table à ce revenu (${m(p.total * 12, 'fr')} par an).`,
    faqs: [
      { q: 'La pension alimentaire a-t-elle un plafond pour les hauts revenus ?', a: `La table du ministère de la Justice n’en prévoit pas : à 6 000 € net, elle donne ${m(p.total, 'fr')} pour un enfant en droit classique, et elle continue de croître avec le revenu. Le juge, en revanche, fixe la pension selon les besoins réels de l’enfant et peut retenir moins que la table quand ces besoins sont couverts.` },
      { q: 'Avec 6 000 € net, combien pour deux enfants en alternance ?', a: `La colonne « alterné » donne ${m(pk(6000, 2, 'alterne').parEnfant, 'fr')} par enfant, soit ${m(pk(6000, 2, 'alterne').total, 'fr')} par mois pour deux enfants, à condition que l’autre parent gagne nettement moins. En résidence alternée, la pension n’est pas déductible, puisque chaque parent compte déjà les enfants dans ses parts.` },
      { q: 'À 6 000 €, quelle économie d’impôt sur la pension d’un enfant mineur ?', a: `Avec environ ${m(72000, 'fr')} de revenu imposable sur une part, le parent est dans la tranche à ${pc(tauxMarginal(72000, 1), 'fr', 0)}. La déduction de ${m(p.total * 12, 'fr')} de pension annuelle lui fait économiser environ ${m(deduction(p.total * 12, 'mineur', 72000).economie, 'fr')}, soit un coût réel de ${m(p.total * 12 - deduction(p.total * 12, 'mineur', 72000).economie, 'fr')} sur l’année.` },
    ] }; },
};

const EN: Record<number, () => Angle> = {
  1000: () => { const p = pk(1000, 1), a = asf(p.parEnfant, 1); return {
    title: `Child support on €1,000 a month in France ${Y}: ASF top-up`, desc: `Child support in France on €1,000 net a month in ${Y}: ${m(p.total, 'en')} for one child with standard visiting, below the ASF, and what the CAF tops up for 2 or 3 children.`,
    h1: `Child support on €1,000 net a month: an amount the CAF tops up`,
    resume: `On €1,000 net a month, the paying parent is only ${m(p.base, 'en')} above the table’s subsistence amount of ${m(MV, 'en')}. The Ministry of Justice table therefore gives modest support: ${m(p.total, 'en')} a month for one child with standard visiting rights, ${m(pk(1000, 1, 'reduit').total, 'en')} with reduced visiting. That is well below the family support allowance (ASF), ${m(ASF, 'en')} per child since 1 April ${Y}. For a parent raising the child alone this matters: the CAF pays the difference, here ${m(a.parEnfant, 'en')} a month, as a top-up ASF. At this income level the real issue is less the amount of support than getting it formally set, because that is what opens the right to the top-up. The calculator below gives the figures for one to six children.`,
    h2a: 'Why support stays below the ASF', pa: `The table first takes off the subsistence amount, then applies a per-child rate to what is left. With ${m(p.base, 'en')} above the subsistence amount, even the highest rate (reduced visiting, one child) only produces ${m(pk(1000, 1, 'reduit').total, 'en')}. Support for one child reaches the ASF at ${m(seuilReduit, 'en')} of income with reduced visiting and ${m(seuilClassique, 'en')} with standard visiting. Below that, a single parent should claim the top-up ASF, paid every three months, provided the gap is above €${P.asf.seuil_non_versement}.`,
    h2b: 'What the parent raising the child receives', pb: `For one child with standard visiting: ${m(p.total, 'en')} of support plus ${m(a.parEnfant, 'en')} of top-up ASF, ${m(p.total + a.parEnfant, 'en')} a month in total, for a parent living alone. With two children, support falls to ${m(pk(1000, 2).parEnfant, 'en')} per child and the ASF tops each one up to ${m(ASF, 'en')}. If the paying parent does not pay at all, the full ASF is paid as an advance and the CAF can pursue them.`,
    faqs: [
      { q: 'Do you have to pay child support on €1,000 a month in France?', a: `Yes. The Ministry of Justice table sets support as soon as income is above the subsistence amount of ${m(MV, 'en')}. On €1,000 net it gives ${m(p.total, 'en')} for one child with standard visiting and ${m(pk(1000, 2).total, 'en')} for two. A judge can set less if the parent’s costs, such as rent, make that amount impossible to pay.` },
      { q: 'Can a parent receiving €47 of support claim the ASF?', a: `Yes, if they live alone: the CAF pays the top-up ASF, the difference between the support set and ${m(ASF, 'en')} per child, about ${m(a.parEnfant, 'en')} a month here. It is due monthly and paid every three months. Support must have been set by a judgment or an agreement, and the gap must be more than €${P.asf.seuil_non_versement}.` },
      { q: 'Is it worth getting such a small amount set by a judge?', a: `Yes. Once set, even at ${m(p.total, 'en')}, support becomes an enforceable claim, indexed every year, and it can be raised later if the paying parent’s income goes up. It is also what allows the CAF to pay the top-up ASF and to recover unpaid support on the parent’s behalf through its agency ARIPA.` },
    ] }; },
  1200: () => { const p1 = pk(1200, 1), p2 = pk(1200, 2); return {
    title: `Child support on €1,200 in France ${Y}: part-time pay`, desc: `Child support in France on €1,200 net a month in ${Y}: ${m(p1.total, 'en')} for one child, ${m(p2.total, 'en')} for two with standard visiting. How part-time work and the ASF top-up interact.`,
    h1: `Child support on €1,200 net a month: the part-time case`,
    resume: `A net income of €1,200 a month often means part-time work or a first job. The Ministry of Justice table leaves the paying parent the subsistence amount of ${m(MV, 'en')} and applies the rate to the rest, ${m(p1.base, 'en')}. For one child with standard visiting rights the indicative support is ${m(p1.total, 'en')} a month; for two children ${m(p2.total, 'en')}, that is ${m(p2.parEnfant, 'en')} each. These amounts are below the family support allowance (${m(ASF, 'en')} per child), which the CAF can add for a parent raising the children alone. The point to watch at this level is whether the income will last: part-time work that is imposed, or a planned return to full time, are things a judge can take into account, and they justify a review once income changes.`,
    h2a: 'Two children: the rate falls, the ASF tops up each child', pa: `With two children the table applies ${pc(p2.tauxEnfant, 'en')} per child instead of ${pc(p1.tauxEnfant, 'en')}, ${m(p2.parEnfant, 'en')} each. For a single parent receiving support, the top-up ASF is worked out child by child: ${m(asf(p2.parEnfant, 2).parEnfant, 'en')} each, ${m(asf(p2.parEnfant, 2).total, 'en')} in total. In the end the CAF pays more than the other parent, which is common below ${m(seuilReduit, 'en')} of income.`,
    h2b: 'Part-time work: what a judge may look at', pb: `Judges set support on actual resources, but they can consider earning capacity when part-time work is a choice rather than a constraint. A parent who goes part-time just before the hearing will need to explain why. Part-time work imposed by an employer or by health is easy to document. When income goes back up the other parent can ask for a review: at €1,800 the table gives ${m(pk(1800, 1).total, 'en')} for one child.`,
    faqs: [
      { q: 'How much child support for two children on €1,200 net?', a: `The Ministry of Justice table gives ${m(p2.total, 'en')} a month for two children with standard visiting, ${m(p2.parEnfant, 'en')} per child. With reduced visiting it would be ${m(pk(1200, 2, 'reduit').total, 'en')}; with shared residence ${m(pk(1200, 2, 'alterne').total, 'en')}. These are benchmarks a judge can depart from depending on costs and needs.` },
      { q: 'Can a part-time parent pay less child support?', a: `The table applies to actual income: on €1,200 net it gives ${m(p1.total, 'en')} for one child. A judge may decide that chosen part-time work should not reduce the contribution, and base it on what the parent could earn. The parent therefore needs to explain and document why their hours are reduced.` },
      { q: 'On €1,200, is child support tax-deductible?', a: `Yes, for a minor child living with the other parent, but the benefit is small: with about ${m(14400, 'en')} of annual taxable income on one share, the marginal rate is ${pc(tauxMarginal(14400, 1), 'en', 0)} and the saving on ${m(p1.total * 12, 'en')} of annual support is about ${m(deduction(p1.total * 12, 'mineur', 14400).economie, 'en')}.` },
    ] }; },
  1500: () => { const p = pk(1500, 1), d = deduction(p.total * 12, 'mineur', 18000); return {
    title: `Child support on €1,500 in France ${Y}: real cost after tax`, desc: `Child support in France on €1,500 net a month in ${Y}: ${m(p.total, 'en')} for one child with standard visiting, ${m(pk(1500, 2).total, 'en')} for two, and its real cost after French tax relief.`,
    h1: `Child support on €1,500 net a month: amount and real cost`,
    resume: `On €1,500 net a month, the paying parent has ${m(p.base, 'en')} above the table’s subsistence amount. For one child with standard visiting, indicative support is ${m(p.total, 'en')} a month, ${pc(p.total / 1500, 'en')} of income; for two children ${m(pk(1500, 2).total, 'en')}. This income level shows a common misunderstanding about tax: support paid is deductible, but in the ${pc(tauxMarginal(18000, 1), 'en', 0)} band the saving is small, about ${m(d.economie, 'en')} a year for one child. The real cost of support is almost its face value, unlike for a higher earner. The receiving parent adds the support to their taxable income after an allowance of at least ${m(P.fiscalite.abattement_min_par_pensionne, 'en')}. The calculator below shows other configurations.`,
    h2a: 'A deduction worth little at this income', pa: `With about ${m(18000, 'en')} of taxable income on one share, the paying parent is in the ${pc(tauxMarginal(18000, 1), 'en', 0)} band. Deducting ${m(p.total * 12, 'en')} of annual support saves about ${m(d.economie, 'en')}: the real cost of support is ${m(p.total * 12 - d.economie, 'en')} over the year. For the same amount, a parent in the 30% band would save nearly three times as much. Worth remembering in a negotiation: one euro of support does not cost everyone the same.`,
    h2b: 'For the parent receiving support', pb: `Support received is taxable: ${m(p.total * 12, 'en')} a year, less the 10% allowance raised here to its minimum of ${m(P.fiscalite.abattement_min_par_pensionne, 'en')}, leaves ${m(pensionImposable(p.total * 12).imposable, 'en')} added to taxable income. For a single parent, whose household gets extra tax shares for the child, the effect on tax is often nil or small. Support of ${m(p.parEnfant, 'en')} per child is still below the ASF here, so a single parent can claim the difference from the CAF.`,
    faqs: [
      { q: 'How much support for one child on a €1,500 net salary?', a: `The Ministry of Justice reference table gives ${m(p.total, 'en')} a month with standard visiting, ${m(pk(1500, 1, 'reduit').total, 'en')} with reduced visiting and ${m(pk(1500, 1, 'alterne').total, 'en')} with shared residence. The sum is (1,500 − ${m(MV, 'en')}) × the column’s rate. The judge can still adjust it to the child’s actual needs.` },
      { q: 'On €1,500, what does support really cost after tax?', a: `Almost its face value: in the ${pc(tauxMarginal(18000, 1), 'en', 0)} band, deducting support cuts tax by about ${m(d.economie, 'en')} a year for one child with standard visiting, a real cost of ${m(p.total * 12 - d.economie, 'en')} over the year. This assumes one tax share and no décote (the low-income reduction): a different household will get a slightly different figure.` },
      { q: 'On €1,500 with three children, what does the table give?', a: `For three children with standard visiting, the table applies ${pc(pk(1500, 3).tauxEnfant, 'en')} per child to income above the subsistence amount: ${m(pk(1500, 3).parEnfant, 'en')} each, ${m(pk(1500, 3).total, 'en')} in total. The paying parent would keep ${m(1500 - pk(1500, 3).total, 'en')} for housing and living costs, which a judge will weigh against their real expenses.` },
    ] }; },
  1800: () => { const pr = pk(1800, 1, 'reduit'), pc_ = pk(1800, 1); return {
    title: `Child support on €1,800 in France ${Y}: at the ASF line`, desc: `Child support in France on €1,800 net in ${Y}: ${m(pc_.total, 'en')} with standard visiting, ${m(pr.total, 'en')} with reduced visiting, so the CAF’s ASF stops topping it up from ${m(seuilReduit, 'en')}.`,
    h1: `Child support on €1,800 net a month: where the ASF drops away`,
    resume: `On €1,800 net a month, support for an only child crosses a small but real line. With reduced visiting rights the Ministry of Justice table gives ${m(pr.total, 'en')} a month, slightly more than the family support allowance (${m(ASF, 'en')}), which therefore can no longer top it up. The switch happens from ${m(seuilReduit, 'en')} of income. With standard visiting, support stays at ${m(pc_.total, 'en')}, still under the ASF, so a single parent can still receive the difference, ${m(asf(pc_.parEnfant, 1).parEnfant, 'en')} a month. The same income gives two different budgets for the parent raising the child, depending on how much visiting time the other parent has. This is one of the cases where describing the visiting arrangement accurately really matters. The calculator below compares the three columns.`,
    h2a: 'Reduced or standard visiting: same income, two budgets', pa: `With reduced visiting, the receiving parent gets ${m(pr.total, 'en')} and no ASF. With standard visiting they get ${m(pc_.total, 'en')} of support plus ${m(asf(pc_.parEnfant, 1).parEnfant, 'en')} of top-up ASF if living alone, ${m(pc_.total + asf(pc_.parEnfant, 1).parEnfant, 'en')} in all. Oddly, the standard arrangement leaves them slightly more, because the CAF fills the gap. That only holds while standard-column support stays under the ASF, up to ${m(seuilClassique, 'en')} of the paying parent’s income.`,
    h2b: 'Two children on €1,800', pb: `With two children the per-child rate falls and each child’s support drops back under the ASF even with reduced visiting: ${m(pk(1800, 2, 'reduit').parEnfant, 'en')} per child, ${m(pk(1800, 2).parEnfant, 'en')} with standard visiting. For siblings, the ASF line sits much higher. The paying parent pays ${m(pk(1800, 2).total, 'en')} with standard visiting and can deduct it from taxable income.`,
    faqs: [
      { q: 'At what income does child support exceed the ASF?', a: `For an only child, from ${m(seuilReduit, 'en')} of the paying parent’s net income with reduced visiting, and from ${m(seuilClassique, 'en')} with standard visiting, using the subsistence amount of ${m(MV, 'en')} and the ASF of ${m(ASF, 'en')}. Below those figures a single receiving parent can claim the top-up ASF from the CAF.` },
      { q: 'On €1,800, how much for one child with reduced visiting?', a: `The table gives ${m(pr.total, 'en')} a month: (1,800 − ${m(MV, 'en')}) × ${pc(pr.tauxEnfant, 'en')}. According to justice.fr, reduced visiting means less contact than every other weekend, for example single days or supervised visits, where the paying parent carries few direct costs. The figure is a benchmark the judge can adjust.` },
      { q: 'Does the receiving parent lose the ASF if support goes up?', a: `The top-up ASF shrinks as support rises and disappears once support reaches ${m(ASF, 'en')} per child; if the gap is below €${P.asf.seuil_non_versement}, nothing is paid. So raising support does not always raise what a single parent receives in total, as long as support stays below the ASF.` },
    ] }; },
  2000: () => { const p = pk(2000, 2); return {
    title: `Child support on €2,000 in France ${Y}: the official row`, desc: `Child support in France on €2,000 net in ${Y}: ${m(pk(2000, 1).total, 'en')} for one child, ${m(p.total, 'en')} for two with standard visiting, checked to the cent against the justice.fr table.`,
    h1: `Child support on €2,000 net a month: the table row, checked`,
    resume: `€2,000 net a month is the classic example, and it is one of the Ministry of Justice table rows our engine replays every time the site is published. After the subsistence amount of ${m(MV, 'en')}, ${m(p.base, 'en')} is left for the rates to apply to. For one child with standard visiting, indicative support is ${m(pk(2000, 1).total, 'en')} a month; for two children ${m(p.parEnfant, 'en')} each, ${m(p.total, 'en')} in total; for three, ${m(pk(2000, 3).total, 'en')}. These figures match those published by justice.fr for this row to the cent, which an automated test checks. Support for an only child with standard visiting sits just under the ${m(ASF, 'en')} ASF, which drops away from ${m(seuilClassique, 'en')}. The calculator below gives all eighteen cells of the row.`,
    h2a: 'The €2,000 row of the table, cell by cell', pa: `For each income the table publishes eighteen per-child amounts: one to six children, three visiting arrangements. For €2,000 they run from ${m(pk(2000, 1, 'reduit').parEnfant, 'en')} (one child, reduced) to ${m(pk(2000, 6, 'alterne').parEnfant, 'en')} (six children, shared residence). Our test compares those eighteen values with justice.fr to the cent: if one changes, publication is blocked until it is checked.`,
    h2b: 'Two children on €2,000: what each home gets', pb: `The paying parent pays ${m(p.total, 'en')} a month, ${m(p.total * 12, 'en')} a year, deductible from income: with about ${m(24000, 'en')} of taxable income on one share, the tax saving is around ${m(deduction(p.total * 12, 'mineur', 24000).economie, 'en')}. The receiving parent declares ${m(pensionImposable(p.total * 12).imposable, 'en')} after the allowance. Each child’s support, ${m(p.parEnfant, 'en')}, is below the ASF, so a single parent can claim the top-up.`,
    faqs: [
      { q: 'How much child support on €2,000 net with two children?', a: `The Ministry of Justice table gives ${m(p.parEnfant, 'en')} per child with standard visiting, ${m(p.total, 'en')} a month for both. With reduced visiting ${m(pk(2000, 2, 'reduit').total, 'en')}; with shared residence ${m(pk(2000, 2, 'alterne').total, 'en')}. These are the amounts justice.fr publishes for a €2,000 income. A judge can still adjust them to the children’s needs and each parent’s costs.` },
      { q: 'How can I check the table calculation at €2,000 myself?', a: `Subtract the subsistence amount: 2,000 − ${m(MV, 'en')} = ${m(p.base, 'en')}. Multiply by your column’s per-child rate, for example ${pc(p.tauxEnfant, 'en')} for two children with standard visiting: ${m(p.parEnfant, 'en')}. Then multiply by the number of children: ${m(p.total, 'en')}. The result should match the cell in the table on justice.fr.` },
      { q: 'At €2,000, is support for an only child above the ASF?', a: `With standard visiting, no: ${m(pk(2000, 1).total, 'en')}, just under the ${m(ASF, 'en')} ASF, leaving a top-up of about ${m(asf(pk(2000, 1).parEnfant, 1).parEnfant, 'en')} for a single parent. With reduced visiting, yes: ${m(pk(2000, 1, 'reduit').total, 'en')}. In the standard column the switch comes at ${m(seuilClassique, 'en')} of income. The top-up is only for a parent living alone.` },
    ] }; },
  2200: () => { const p = pk(2200, 1); return {
    title: `Child support on €2,200 in France ${Y}: no more ASF top-up`, desc: `Child support in France on €2,200 net in ${Y}: ${m(p.total, 'en')} for one child with standard visiting, above the ASF, so the CAF top-up ends. Two and three children.`,
    h1: `Child support on €2,200 net a month: the end of the CAF top-up`,
    resume: `On €2,200 net, support for an only child with standard visiting reaches ${m(p.total, 'en')} a month according to the Ministry of Justice table. It is the first income on our pages where support exceeds the family support allowance (${m(ASF, 'en')}) in the most common column; the exact line is ${m(seuilClassique, 'en')}. In practice a single receiving parent can no longer claim the top-up ASF, unless support goes unpaid, in which case the ASF is still paid as an advance. For two children, support is ${m(pk(2200, 2).parEnfant, 'en')} per child, still under the ASF, so siblings keep the top-up. Official simulators give the same support figure as ours at this income, but only ours shows the effect on the ASF and on tax. The calculator below makes the comparison.`,
    h2a: 'Above the line, the ASF only works as an advance', pa: `As long as support is paid, a single parent whose child receives ${m(p.total, 'en')} no longer gets the top-up ASF. If the paying parent stops paying, the full ASF of ${m(ASF, 'en')} per child is paid again as an advance while the CAF or ARIPA recovers the support. It then only covers part of the support owed, the rest being pursued from the paying parent.`,
    h2b: 'One child, two children: where the line sits', pb: `For two children with standard visiting, per-child support only exceeds the ASF from ${m(Math.ceil(MV + ASF / P.bareme.taux['2'][1]), 'en')} of income; for three, from ${m(Math.ceil(MV + ASF / P.bareme.taux['3'][1]), 'en')}. On €2,200 two siblings receive ${m(pk(2200, 2).total, 'en')} of support, and a single parent can claim ${m(asf(pk(2200, 2).parEnfant, 2).total, 'en')} of top-up ASF on top.`,
    faqs: [
      { q: 'On €2,200 net, how much for one child?', a: `${m(p.total, 'en')} a month with standard visiting, ${m(pk(2200, 1, 'reduit').total, 'en')} with reduced visiting and ${m(pk(2200, 1, 'alterne').total, 'en')} with shared residence, according to the Ministry of Justice table. The calculation subtracts the subsistence amount of ${m(MV, 'en')} and applies the column rate to the remaining ${m(p.base, 'en')}. The judge can depart from it.` },
      { q: 'Why does a single parent lose the ASF once support passes €200?', a: `Because the top-up ASF brings support up to ${m(ASF, 'en')} per child: above that there is nothing left to top up. The full ASF is still paid as an advance if the support that was set is not paid, and the CAF then recovers it from the other parent.` },
      { q: 'On €2,200, is support for two children above the ASF?', a: `No: ${m(pk(2200, 2).parEnfant, 'en')} per child with standard visiting, below the ${m(ASF, 'en')} ASF. A single parent can therefore claim the top-up ASF for each of the two children, about ${m(asf(pk(2200, 2).parEnfant, 2).parEnfant, 'en')} per child per month, paid by the CAF every three months. Living as a couple ends it.` },
    ] }; },
  2500: () => { const p = pk(2500, 1), d = deduction(p.total * 12, 'mineur', 30000); return {
    title: `Child support on €2,500 in France ${Y}: the 30% tax band`, desc: `Child support in France on €2,500 net in ${Y}: ${m(p.total, 'en')} for one child with standard visiting. Entering the 30% income tax band: what the deduction is worth.`,
    h1: `Child support on €2,500 net a month: the 30% band changes the cost`,
    resume: `On €2,500 net a month, roughly ${m(30000, 'en')} of annual taxable income, a paying parent who files alone moves into the ${pc(tauxMarginal(30000, 1), 'en', 0)} income tax band. That tax detail changes the real cost of support. The Ministry of Justice table gives ${m(p.total, 'en')} a month for one child with standard visiting, ${m(pk(2500, 2).total, 'en')} for two. Deducted from income, support for one child saves about ${m(d.economie, 'en')} of tax over the year: its real cost falls to ${m(p.total * 12 - d.economie, 'en')}, or ${m((p.total * 12 - d.economie) / 12, 'en')} a month. Above this income, part of each extra euro of support is funded by the tax not paid. That is a concrete point in any negotiation between parents. The calculator below shows the real cost.`,
    h2a: 'Moving into the 30% band', pa: `The scale for ${P.fiscalite.revenus} income moves from 11% to 30% above ${m(P.fiscalite.tranches[1].jusqua!, 'en')} of taxable income per share. A single parent on ${m(30000, 'en')} is just above it: deducted support comes off the 30% slice first, then the 11% slice. The higher the support, the more of it is deducted at 11%, so the average saving lands between the two rates.`,
    h2b: 'Two children on €2,500', pb: `For two children with standard visiting, support reaches ${m(pk(2500, 2).total, 'en')} a month, ${m(pk(2500, 2).total * 12, 'en')} a year. The estimated tax saving is about ${m(deduction(pk(2500, 2).total * 12, 'mineur', 30000).economie, 'en')}. The receiving parent declares ${m(pensionImposable(pk(2500, 2).total * 12).imposable, 'en')} after the allowance. Each child’s support, ${m(pk(2500, 2).parEnfant, 'en')}, is still under the ASF, so a single parent can claim the top-up.`,
    faqs: [
      { q: 'How much support for one child on a €2,500 salary?', a: `The Ministry of Justice table gives ${m(p.total, 'en')} a month with standard visiting, ${m(pk(2500, 1, 'reduit').total, 'en')} with reduced visiting and ${m(pk(2500, 1, 'alterne').total, 'en')} with shared residence. The calculation starts from €2,500 minus the ${m(MV, 'en')} subsistence amount, ${m(p.base, 'en')}, multiplied by the column’s rate. The judge can still adjust the result to the child’s needs.` },
      { q: 'What is the deduction worth on €2,500 net?', a: `About ${m(d.economie, 'en')} a year for one child with standard visiting, assuming one tax share, around ${m(30000, 'en')} of taxable income and no décote. The real cost of support is then ${m(p.total * 12 - d.economie, 'en')} over the year instead of ${m(p.total * 12, 'en')}. With shared residence there is no deduction.` },
      { q: 'On €2,500, is shared residence cheaper?', a: `Residence is decided in the child’s interest, not on cost. In figures, the table gives ${m(pk(2500, 1, 'alterne').total, 'en')} with shared residence against ${m(p.total, 'en')} with standard visiting, but the parent then pays half of the child’s day-to-day costs directly and loses the tax deduction. The real gap is much smaller than it looks.` },
    ] }; },
  3000: () => { const pa = pk(3000, 1, 'alterne'), pcl = pk(3000, 1); return {
    title: `Child support on €3,000 in France ${Y}: shared or standard`, desc: `Child support in France on €3,000 net in ${Y}: ${m(pcl.total, 'en')} for one child with standard visiting, ${m(pa.total, 'en')} with shared residence. Who pays when the two incomes differ.`,
    h1: `Child support on €3,000 net a month: shared residence or standard visiting`,
    resume: `On €3,000 net a month, shared residence often comes up, and with it the question of support between parents with unequal incomes. The Ministry of Justice table gives ${m(pcl.total, 'en')} a month for one child with standard visiting, but ${m(pa.total, 'en')} with shared residence, where each parent already covers half of the child’s life. For two children the amounts are ${m(pk(3000, 2).total, 'en')} and ${m(pk(3000, 2, 'alterne').total, 'en')}. With shared residence, support is not automatic: it is justified when the other parent earns clearly less, and the better-off parent pays. Yet the table only looks at the paying parent’s income: if the other parent earns ${m(2800, 'en')}, a judge may set no support at all. The calculator compares the columns.`,
    h2a: 'With shared residence, the income gap decides', pa: `The table reads one parent’s income. With shared residence that is not enough: two parents on ${m(3000, 'en')} and ${m(2900, 'en')} have no reason to pay each other support, though the shared column would show ${m(pa.total, 'en')}. Judges, or parents drafting an agreement, look at the gap instead. A common approach is low support plus a split of extra costs in proportion to income, easier to run than a large monthly payment.`,
    h2b: 'What each arrangement means beyond the amount', pb: `With standard visiting, support of ${m(pcl.total, 'en')} is deductible for the parent who pays it (estimated saving: ${m(deduction(pcl.total * 12, 'mineur', 36000).economie, 'en')} a year on one share) and taxable for the other. With shared residence it is not deductible, because each parent counts the child in their tax shares. Residence is decided in the child’s interest first; these figures only measure what it changes to both budgets.`,
    faqs: [
      { q: 'On €3,000 net, how much support with shared residence?', a: `The “alterné” column of the Ministry of Justice table gives ${m(pa.total, 'en')} a month for one child and ${m(pk(3000, 2, 'alterne').total, 'en')} for two. That figure only makes sense if the other parent earns clearly less: with shared residence, support is only owed to a parent whose income is not enough to meet the child’s needs while the child is with them.` },
      { q: 'On €3,000, how much for one child with standard visiting?', a: `${m(pcl.total, 'en')} a month according to the table: (3,000 − ${m(MV, 'en')}) × ${pc(pcl.tauxEnfant, 'en')}. With reduced visiting it would be ${m(pk(3000, 1, 'reduit').total, 'en')}. Support is deductible for the paying parent, bringing its real cost to around ${m(pcl.total * 12 - deduction(pcl.total * 12, 'mineur', 36000).economie, 'en')} a year. That assumes one tax share.` },
      { q: 'With shared residence, can support be replaced by sharing costs?', a: `Yes, if both parents agree and write it into an agreement, or if the judge decides so: support can take the form of paying some of the child’s costs directly, in full or in part. Service-public.fr gives the example of splitting school fees half and half. The clause should list the costs and the split.` },
    ] }; },
  3500: () => { const p = pk(3500, 3); return {
    title: `Child support on €3,500 in France ${Y}: three children`, desc: `Child support in France on €3,500 net in ${Y}: ${m(p.total, 'en')} for three children with standard visiting, what the parent keeps, and what a judge may adjust. Full figures.`,
    h1: `Child support on €3,500 net a month: three children and what is left`,
    resume: `On €3,500 net with three children, support becomes one of the biggest items in the paying parent’s budget. The Ministry of Justice table applies ${pc(p.tauxEnfant, 'en')} per child to income above the subsistence amount: ${m(p.parEnfant, 'en')} per child and ${m(p.total, 'en')} a month for all three with standard visiting, ${pc(p.total / 3500, 'en')} of total income. That leaves ${m(3500 - p.total, 'en')} for housing, travel to see the children and everyday life. At this level, what the parent has left becomes the key argument before the judge: rent of ${m(1000, 'en')} leaves only ${m(3500 - p.total - 1000, 'en')}. On the other hand, deducting support, uncapped for minor children, cuts income tax noticeably. The calculator below gives other configurations.`,
    h2a: 'What is left, with and without rent', pa: `The table’s subsistence amount, ${m(MV, 'en')}, ignores housing. With three children on €3,500, the paying parent keeps ${m(3500 - p.total, 'en')} before housing. A homeowner with no mortgage is comfortable; a tenant paying ${m(1000, 'en')} in a city is left with ${m(3500 - p.total - 1000, 'en')}, and still hosts the children every other weekend. A judge can set less than the table if those costs are documented.`,
    h2b: 'The effect of the tax deduction', pb: `The ${m(p.total * 12, 'en')} of annual support is fully deductible for minor children living with the other parent. With about ${m(42000, 'en')} of taxable income on one share, the estimated saving is ${m(deduction(p.total * 12, 'mineur', 42000).economie, 'en')} over the year, ${m(deduction(p.total * 12, 'mineur', 42000).economie / 12, 'en')} a month. The real cost of the three payments falls to ${m(p.total - deduction(p.total * 12, 'mineur', 42000).economie / 12, 'en')} a month.`,
    faqs: [
      { q: 'How much child support for three children on €3,500 net?', a: `The Ministry of Justice table gives ${m(p.total, 'en')} a month with standard visiting, ${m(p.parEnfant, 'en')} per child. With reduced visiting it would be ${m(pk(3500, 3, 'reduit').total, 'en')}; with shared residence ${m(pk(3500, 3, 'alterne').total, 'en')}. The judge can adapt these to the parent’s costs and each child’s needs. Each figure is per month, before indexation.` },
      { q: 'On €3,500, what does the parent keep after support for three children?', a: `${m(3500 - p.total, 'en')} a month before any housing costs, since the table takes ${m(p.total, 'en')}. After rent of ${m(1000, 'en')}, ${m(3500 - p.total - 1000, 'en')} would remain. That remaining income, backed by the lease and rent receipts, is what the paying parent can show the judge to argue for less than the table.` },
      { q: 'Is support for three children fully deductible?', a: `Yes, for minor children whose main home is with the other parent and who are not counted in the paying parent’s tax shares: the deduction is not capped. With ${m(p.total * 12, 'en')} of annual support and about ${m(42000, 'en')} of taxable income on one share, the estimated saving is ${m(deduction(p.total * 12, 'mineur', 42000).economie, 'en')}.` },
    ] }; },
  4000: () => { const a = pk(3000, 1), b = pk(4000, 1); return {
    title: `Child support on €4,000 in France ${Y}: after a pay rise`, desc: `Child support in France on €4,000 net in ${Y}: ${m(b.total, 'en')} for one child with standard visiting. How to ask for more once the other parent has had a pay rise.`,
    h1: `Child support on €4,000 net a month: after a pay rise`,
    resume: `A net income of €4,000 often follows a promotion or a new job, and raises a specific question: can the receiving parent ask for more? Yes, if the rise is new since the last decision; it is one of the accepted grounds for a review. According to the Ministry of Justice table, a parent who paid ${m(a.total, 'en')} for one child with standard visiting when earning ${m(3000, 'en')} would pay ${m(b.total, 'en')} on €4,000, ${m(b.total - a.total, 'en')} more a month. For two children support goes from ${m(pk(3000, 2).total, 'en')} to ${m(pk(4000, 2).total, 'en')}. The change is not automatic: it needs an approved agreement or a judge’s decision, plus proof of the new income. The calculator below gives the figures at €4,000.`,
    h2a: 'Asking for an increase', pa: `The receiving parent must show that the other parent’s resources have risen since the last decision. A tax notice, if available, or any evidence about the new job serves as proof. They apply to the family court judge (JAF), with no lawyer required, using the application form and a calculation of the table at both incomes. The judge also looks at the child’s needs, which have often grown in the meantime.`,
    h2b: 'On €4,000: support and tax', pb: `On €4,000 net, about ${m(48000, 'en')} of taxable income, the paying parent is in the ${pc(tauxMarginal(48000, 1), 'en', 0)} band. Deducting ${m(b.total * 12, 'en')} of annual support for a minor child saves about ${m(deduction(b.total * 12, 'mineur', 48000).economie, 'en')}. The ${m(b.total - a.total, 'en')} monthly increase in support therefore really costs only about ${m((b.total - a.total) * 0.7, 'en')}.`,
    faqs: [
      { q: 'How much support for one child on a €4,000 net salary?', a: `The Ministry of Justice table gives ${m(b.total, 'en')} a month with standard visiting, ${m(pk(4000, 1, 'reduit').total, 'en')} with reduced visiting and ${m(pk(4000, 1, 'alterne').total, 'en')} with shared residence. The sum is (4,000 − ${m(MV, 'en')}) × the column’s per-child rate. The judge can adjust for needs and costs.` },
      { q: 'The other parent got a pay rise: does support go up by itself?', a: 'No. Only the annual indexation to the price index applies without a judge. An increase based on income requires a review: a new approved agreement or a decision of the family court judge, applied for by the receiving parent with proof of the rise. The new amount applies from the date the judge sets.' },
      { q: 'Can I ask for a review without knowing the new salary?', a: 'Yes. The parent asking for the review presents what they know (new job, lifestyle) and sets out the child’s needs. If the other parent’s income is unknown, the judge can set support at the amount requested, or reduce it if it seems out of proportion. At the hearing each parent has to produce evidence of income.' },
    ] }; },
  5000: () => { const p = pk(5000, 1); return {
    title: `Child support on €5,000 in France ${Y}: adult child, tax cap`, desc: `Child support in France on €5,000 net in ${Y}: ${m(p.total, 'en')} for one child. After 18, the €6,855 yearly deduction cap no longer covers the whole amount of support.`,
    h1: `Child support on €5,000 net a month: when the child turns 18`,
    resume: `On €5,000 net a month, support for an only child with standard visiting reaches ${m(p.total, 'en')} under the Ministry of Justice table, ${m(p.total * 12, 'en')} a year. While the child is a minor it is fully deductible for the paying parent. But once the child is an adult who is not attached to the parent’s tax household and lives elsewhere, the deduction is capped at ${m(P.fiscalite.plafond_majeur, 'en')} a year per child, ${m(capMajeurMois, 'en')} a month. Table support exceeds that cap from ${m(Math.ceil(MV + capMajeurMois / P.bareme.taux['1'][1]), 'en')} of income with standard visiting: on €5,000, ${m(p.total * 12 - P.fiscalite.plafond_majeur, 'en')} a year is no longer deductible, and the young adult declares only the deducted part. Support itself continues until the child is self-supporting. The calculator below gives the figures at €5,000.`,
    h2a: 'The deduction cap for an adult child', pa: `For ${P.fiscalite.revenus} income, support paid to an adult child who is not attached to the household is deductible up to ${m(P.fiscalite.plafond_majeur, 'en')} a year. On €5,000, table support for one child (${m(p.total * 12, 'en')} a year) exceeds that cap. The parent then chooses: deduct capped support, or attach the child to their tax household, which rules out the deduction. The better option depends on their marginal rate and the young adult’s income.`,
    h2b: 'Higher incomes: the form of support matters', pb: `With higher incomes, support often takes a mixed form: a monthly amount plus direct payment of some costs, such as university or student accommodation, as service-public.fr describes. For an adult child, paying the rent on a studio directly and giving a smaller cash amount can be clearer for everyone; both are deductible together, within the cap.`,
    faqs: [
      { q: 'On €5,000 net, how much support for one child?', a: `The Ministry of Justice table gives ${m(p.total, 'en')} a month with standard visiting, ${m(pk(5000, 1, 'reduit').total, 'en')} with reduced visiting and ${m(pk(5000, 1, 'alterne').total, 'en')} with shared residence. For two children with standard visiting, ${m(pk(5000, 2).total, 'en')}. A judge can depart from the table based on the child’s actual needs and the family’s lifestyle.` },
      { q: 'On €5,000, how much of an adult child’s support is deductible?', a: `At most ${m(P.fiscalite.plafond_majeur, 'en')} a year for an adult child who is not attached and lives elsewhere, on ${P.fiscalite.revenus} income. With support of ${m(p.total * 12, 'en')} a year, ${m(p.total * 12 - P.fiscalite.plafond_majeur, 'en')} is not deductible. The young adult declares the deducted amount, with a 10% allowance.` },
      { q: 'Is it better to attach an adult child or deduct support?', a: 'The two are mutually exclusive: an attached child adds at least half a tax share to the parent’s household, but the parent can no longer deduct support for them. Attaching often suits a parent with modest tax, deducting suits a parent in a high band. The official tax simulator lets you compare precisely.' },
    ] }; },
  6000: () => { const p = pk(6000, 1); return {
    title: `Child support on €6,000 in France ${Y}: share of income`, desc: `Child support in France on €6,000 net in ${Y}: ${m(p.total, 'en')} for one child, ${m(pk(6000, 2).total, 'en')} for two. The higher the income, the closer support gets to the full column rate.`,
    h1: `Child support on €6,000 net a month: the table at higher incomes`,
    resume: `On €6,000 net a month, the Ministry of Justice table gives ${m(p.total, 'en')} a month for one child with standard visiting, ${m(pk(6000, 2).total, 'en')} for two and ${m(pk(6000, 3).total, 'en')} for three. At this level a mathematical feature of the table shows: the fixed subsistence amount of ${m(MV, 'en')} weighs less and less, so support as a share of total income gets closer and closer to the column rate. For one child with standard visiting it reaches ${pc(p.total / 6000, 'en')} of total income, against a rate of ${pc(p.tauxEnfant, 'en')}; on €1,500 it was only ${pc(pk(1500, 1).total / 1500, 'en')}. Judges can still depart from the table for high incomes, depending on the child’s real needs and lifestyle. The calculator below gives the detail.`,
    h2a: 'Why the share of income rises with income', pa: `The table applies a rate to income minus a fixed amount. That fixed amount is ${pc(MV / 1500, 'en', 0)} of a €1,500 income but only ${pc(MV / 6000, 'en', 0)} of a €6,000 income. Support as a share of total income therefore approaches the full rate as income rises. The table below shows it for one child with standard visiting.`,
    h2b: 'High incomes: the child’s needs and lifestyle', pb: `The table has no ceiling, but a judge sets support according to the child’s needs, which do not grow forever with the parent’s income. The judge considers the lifestyle the child had before the separation, schooling and activities. For an adult child, the tax deduction is capped at ${m(P.fiscalite.plafond_majeur, 'en')} a year, well below table support at this income (${m(p.total * 12, 'en')} a year).`,
    faqs: [
      { q: 'Is child support capped for high earners in France?', a: `The Ministry of Justice table has no cap: on €6,000 net it gives ${m(p.total, 'en')} for one child with standard visiting, and keeps rising with income. A judge, however, sets support according to the child’s actual needs and can set less than the table when those needs are covered.` },
      { q: 'On €6,000 net, how much for two children with shared residence?', a: `The shared column gives ${m(pk(6000, 2, 'alterne').parEnfant, 'en')} per child, ${m(pk(6000, 2, 'alterne').total, 'en')} a month for two children, provided the other parent earns clearly less. With shared residence, support is not deductible, since each parent already counts the children in their tax shares. Support is owed only to a parent whose income falls short.` },
      { q: 'On €6,000, what tax saving on support for a minor child?', a: `With about ${m(72000, 'en')} of taxable income on one share, the parent is in the ${pc(tauxMarginal(72000, 1), 'en', 0)} band. Deducting ${m(p.total * 12, 'en')} of annual support saves about ${m(deduction(p.total * 12, 'mineur', 72000).economie, 'en')}, a real cost of ${m(p.total * 12 - deduction(p.total * 12, 'mineur', 72000).economie, 'en')} over the year. The estimate ignores the décote and the family-quotient cap.` },
    ] }; },
};

export function angle(amount: number, lang: L): Angle {
  const f = (lang === 'en' ? EN : FR)[amount];
  if (!f) throw new Error(`Pas d’angle pour ${amount}`);
  const A = f();
  // L'anglais est plus compact : une phrase de plus garde le bloc citable au-dessus de 120 mots (§21).
  if (lang === 'en') A.resume += ` Over a full year, the table means ${m(pk(amount, 1).total * 12, 'en')} for one child and ${m(pk(amount, 2).total * 12, 'en')} for two with standard visiting.`;
  return A;
}
export { impotBareme };
