/** Cartes « calculs associés » et listes de sources, communes aux pages. */
import { route, type Locale } from '../i18n/routes';
import { label } from '../i18n/nav';
import P from '../data/params-2026.json';

const D: Record<Locale, Record<string, string>> = {
  fr: { home: 'Le budget du divorce en une saisie.', pension: 'Pension selon revenu, enfants et droit de visite.', pc: 'Trois méthodes indicatives et la fiscalité.', soulte: 'Ce que doit celui qui garde le logement.', rachat: 'Financer la soulte et reprendre le prêt.', partage: 'Liquider la communauté, récompenses comprises.', cout: 'Frais réglementés et honoraires, par procédure.', cm: 'Le divorce sans juge, étape par étape.', faute: 'Griefs, preuves, durée et coût du contentieux.', enligne: 'Ce que recouvre un divorce « en ligne ».', delais: 'Les délais légaux, procédure par procédure.', impots: 'Deux déclarations, parts et pension déduite.', cafalt: 'Allocations et parts fiscales partagées.', reversion: 'Régime général et Agirc-Arrco pour l’ex.', pacs: 'Dissolution, biens indivis et impôts.', sepcorps: 'Rester marié mais vivre séparé.', bareme: 'La table du ministère, ligne par ligne.', modes: 'Réduit, classique, alterné : l’écart chiffré.', alternee: 'Qui verse quoi quand l’enfant vit chez les deux.', enfant1: 'Le montant pour un enfant unique.', enfant2: 'Deux enfants : taux et total.', enfant3: 'Trois enfants : ce que la table prévoit.', enfant4: 'Quatre à six enfants.', majeur: 'Pension, déduction et impôt après 18 ans.', unions: 'Enfants de deux unions : deux lectures.', revalo: 'Le nouveau montant avec l’indice INSEE.', asf: 'L’allocation de soutien familial de la CAF.', deduction: 'L’économie d’impôt du parent qui verse.', imposable: 'Ce que déclare le parent qui reçoit.', arrieres: 'Ce qui reste réclamable, sur 5 ans.', caf: 'Intermédiation par l’Aripa, étape par étape.', impayee: 'Les recours quand la pension ne vient pas.', paiementdirect: 'Saisir la pension chez l’employeur.', abandon: 'Le délit, ses conditions et la plainte.', etranger: 'Recouvrer quand l’autre parent vit hors de France.', revision: 'Faire baisser ou augmenter la pension.', chomage: 'Pension avec le chômage ou le RSA.', conjoint: 'Ce que change un nouveau compagnon.', amiable: 'Fixer la pension sans juge.', juge: 'Les critères réels du juge aux affaires familiales.', frais: 'Partager les dépenses hors pension.', duree: 'Quand la pension s’arrête.', epoux: 'Devoir de secours et prestation compensatoire.', ascendants: 'L’obligation alimentaire envers ses parents.', method: 'Formules, sources et limites.', faq: 'Toutes les questions en un lieu.' },
  en: { home: 'Your divorce budget in one go.', pension: 'Support by income, children and visiting time.', pc: 'Three rule-of-thumb methods and the tax.', soulte: 'What the spouse keeping the home owes.', rachat: 'Funding the soulte and taking over the loan.', partage: 'Winding up the community, reimbursements included.', cout: 'Regulated fees and lawyers, by procedure.', cm: 'The no-court divorce, step by step.', faute: 'Grounds, evidence, length and cost.', enligne: 'What an “online” divorce really is.', delais: 'Legal time limits, procedure by procedure.', impots: 'Two returns, tax shares, support deducted.', cafalt: 'Shared benefits and tax shares.', reversion: 'Basic and Agirc-Arrco pensions for an ex.', pacs: 'Dissolution, joint property and tax.', sepcorps: 'Staying married but living apart.', bareme: 'The Ministry table, row by row.', modes: 'Reduced, standard, shared: the gap in euros.', alternee: 'Who pays what when the child lives in both homes.', enfant1: 'The amount for an only child.', enfant2: 'Two children: rate and total.', enfant3: 'Three children: what the table gives.', enfant4: 'Four to six children.', majeur: 'Support, deduction and tax after 18.', unions: 'Children from two relationships.', revalo: 'The new amount with the INSEE index.', asf: 'The CAF family support allowance.', deduction: 'The paying parent’s tax saving.', imposable: 'What the receiving parent declares.', arrieres: 'What can still be claimed, over 5 years.', caf: 'ARIPA payment service, step by step.', impayee: 'Remedies when support does not arrive.', paiementdirect: 'Collecting support from the employer.', abandon: 'The offence, its conditions, the complaint.', etranger: 'Recovering support from a parent abroad.', revision: 'Getting the amount lowered or raised.', chomage: 'Support on unemployment benefit or RSA.', conjoint: 'What a new partner changes.', amiable: 'Setting support without a judge.', juge: 'What the family judge actually weighs.', frais: 'Sharing costs outside the support.', duree: 'When support stops.', epoux: 'Spousal duty of support and compensatory payment.', ascendants: 'The duty to support one’s own parents.', method: 'Formulas, sources and limits.', faq: 'Every question in one place.' },
};
export const rel = (ids: string[], lang: Locale) => ids.map((id) => ({ href: route(id, lang), name: label(id, lang), description: D[lang][id] ?? '' }));

type S = { url: string; label: Record<string, string> };
const SRC = P.sources as Record<string, S>;
const EXTRA: Record<string, S> = {
  f1249: { url: 'https://www.service-public.gouv.fr/particuliers/vosdroits/F1249', label: { fr: 'Service-public.fr — Que faire si la pension alimentaire n’est pas payée ? (F1249)', en: 'Service-public.fr — What to do if child support is not paid (F1249)' } },
  f998: { url: 'https://www.service-public.gouv.fr/particuliers/vosdroits/F998', label: { fr: 'Service-public.fr — Procédure de paiement direct (F998)', en: 'Service-public.fr — Direct payment procedure (F998)' } },
  f2010: { url: 'https://www.service-public.gouv.fr/particuliers/vosdroits/F2010', label: { fr: 'Service-public.fr — Revalorisation annuelle de la pension alimentaire (F2010)', en: 'Service-public.fr — Annual indexation of child support (F2010)' } },
  f21023: { url: 'https://www.service-public.gouv.fr/particuliers/vosdroits/F21023', label: { fr: 'Service-public.fr — Révision du montant de la pension alimentaire (F21023)', en: 'Service-public.fr — Reviewing the amount of child support (F21023)' } },
  f10435: { url: 'https://www.service-public.gouv.fr/particuliers/vosdroits/F10435', label: { fr: 'Service-public.fr — Pension alimentaire à un enfant devenu majeur (F10435)', en: 'Service-public.fr — Child support for a child who has turned 18 (F10435)' } },
  f35777: { url: 'https://www.service-public.gouv.fr/particuliers/vosdroits/F35777', label: { fr: 'Service-public.fr — Pension alimentaire perçue : imposition (F35777)', en: 'Service-public.fr — Tax on support received (F35777)' } },
  f1419: { url: 'https://www.service-public.gouv.fr/particuliers/vosdroits/F1419', label: { fr: 'Service-public.fr — Barème de l’impôt sur le revenu 2026 (F1419)', en: 'Service-public.fr — 2026 income tax scale (F1419)' } },
  f444: { url: 'https://www.service-public.gouv.fr/particuliers/vosdroits/F444', label: { fr: 'Service-public.fr — Pension versée à un parent ou grand-parent : déduction (F444)', en: 'Service-public.fr — Support paid to a parent or grandparent: deduction (F444)' } },
  f446: { url: 'https://www.service-public.gouv.fr/particuliers/vosdroits/F446', label: { fr: 'Service-public.fr — Pension versée à son époux ou ex-époux (F446)', en: 'Service-public.fr — Payments to a spouse or former spouse (F446)' } },
  f2236: { url: 'https://www.service-public.gouv.fr/particuliers/vosdroits/F2236', label: { fr: 'Service-public.fr — Pension alimentaire et prestation compensatoire : différences (F2236)', en: 'Service-public.fr — Child support versus compensatory payment (F2236)' } },
  f1004: { url: 'https://www.service-public.gouv.fr/particuliers/vosdroits/F1004', label: { fr: 'Service-public.fr — Pension impayée, débiteur à l’étranger (F1004)', en: 'Service-public.fr — Unpaid support, paying parent abroad (F1004)' } },
  f38331: { url: 'https://www.service-public.gouv.fr/particuliers/vosdroits/F38331', label: { fr: 'Service-public.fr — Fixer à l’amiable la garde et la pension (F38331)', en: 'Service-public.fr — Agreeing custody and support out of court (F38331)' } },
  justice: { url: 'https://www.justice.fr/simulateurs/pension-alimentaire', label: { fr: 'Justice.fr — Comprendre et estimer la pension alimentaire', en: 'Justice.fr — Understanding and estimating child support' } },
  f13104: { url: 'https://www.service-public.gouv.fr/particuliers/vosdroits/F13104', label: { fr: 'Service-public.fr — Pension de réversion du régime général (F13104)', en: 'Service-public.fr — Survivor’s pension, general scheme (F13104)' } },
  agirc: { url: 'https://www.agirc-arrco.fr/particuliers/ma-retraite/demander-ma-retraite/la-pension-de-reversion/', label: { fr: 'Agirc-Arrco — La pension de réversion (conjoint et ex-conjoints)', en: 'Agirc-Arrco — Survivor’s pension for spouses and former spouses' } },
  f13213: { url: 'https://www.service-public.gouv.fr/particuliers/vosdroits/F13213', label: { fr: 'Service-public.fr — Allocations familiales, montants 2026 (F13213)', en: 'Service-public.fr — Family allowances, 2026 amounts (F13213)' } },
  f21248: { url: 'https://www.service-public.gouv.fr/particuliers/vosdroits/F21248', label: { fr: 'Service-public.fr — Allocations familiales en garde alternée (F21248)', en: 'Service-public.fr — Family allowances with shared custody (F21248)' } },
  f2705: { url: 'https://www.service-public.gouv.fr/particuliers/vosdroits/F2705', label: { fr: 'Service-public.fr — Quotient familial et plafonnement (F2705)', en: 'Service-public.fr — Tax shares and their cap (F2705)' } },
  f35120: { url: 'https://www.service-public.gouv.fr/particuliers/vosdroits/F35120', label: { fr: 'Service-public.fr — Quotient familial d’un parent isolé (F35120)', en: 'Service-public.fr — Tax shares of a single parent (F35120)' } },
  f2633: { url: 'https://www.service-public.gouv.fr/particuliers/vosdroits/F2633', label: { fr: 'Service-public.fr — Quotient familial en cas de divorce ou de séparation (F2633)', en: 'Service-public.fr — Tax shares after divorce or separation (F2633)' } },
  f388: { url: 'https://www.service-public.gouv.fr/particuliers/vosdroits/F388', label: { fr: 'Service-public.fr — Déclarer un changement de situation familiale (F388)', en: 'Service-public.fr — Reporting a change in family situation (F388)' } },
  impotsSepare: { url: 'https://www.impots.gouv.fr/particulier/je-me-separe', label: { fr: 'Impots.gouv.fr — Je me sépare', en: 'Impots.gouv.fr — Separating (French tax administration)' } },
  f18074: { url: 'https://www.service-public.gouv.fr/particuliers/vosdroits/F18074', label: { fr: 'Service-public.fr — Aide juridictionnelle, plafonds 2026 (F18074)', en: 'Service-public.fr — Legal aid, 2026 thresholds (F18074)' } },
  f1620: { url: 'https://www.service-public.gouv.fr/particuliers/vosdroits/F1620', label: { fr: 'Service-public.fr — Dissolution d’un Pacs (F1620)', en: 'Service-public.fr — Ending a PACS (F1620)' } },
  f980: { url: 'https://www.service-public.gouv.fr/particuliers/vosdroits/F980', label: { fr: 'Service-public.fr — Séparation de corps (F980)', en: 'Service-public.fr — Legal separation (F980)' } },
  n159: { url: 'https://www.service-public.gouv.fr/particuliers/vosdroits/N159', label: { fr: 'Service-public.fr — Divorce et séparation de corps (N159)', en: 'Service-public.fr — Divorce and legal separation (N159)' } },
  justiceDivorce: { url: 'https://www.justice.fr/themes/procedure-divorce', label: { fr: 'Justice.fr — La procédure de divorce', en: 'Justice.fr — Divorce procedure' } },
  ccPC: { url: 'https://www.legifrance.gouv.fr/codes/id/LEGISCTA000006165474', label: { fr: 'Légifrance — Code civil, art. 270 à 281 : des prestations compensatoires', en: 'Légifrance — Civil Code, arts. 270 to 281: compensatory payments' } },
  ccCM: { url: 'https://www.legifrance.gouv.fr/codes/section_lc/LEGITEXT000006070721/LEGISCTA000006149977/', label: { fr: 'Légifrance — Code civil, art. 229-1 à 232 : du divorce par consentement mutuel', en: 'Légifrance — Civil Code, arts. 229-1 to 232: divorce by mutual consent' } },
  ccSC: { url: 'https://www.legifrance.gouv.fr/codes/section_lc/LEGITEXT000006070721/LEGISCTA000006136157/', label: { fr: 'Légifrance — Code civil, art. 296 à 308 : de la séparation de corps', en: 'Légifrance — Civil Code, arts. 296 to 308: legal separation' } },
  cgi746: { url: 'https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000041470472', label: { fr: 'Légifrance — CGI, art. 746 : droit de partage (1,10 % après divorce ou rupture de Pacs)', en: 'Légifrance — Tax Code, art. 746: partition duty (1.10% after divorce or PACS)' } },
  bofipPartage: { url: 'https://bofip.impots.gouv.fr/bofip/817-PGP.html/identifiant=BOI-ENR-PTG-10-10-20200630', label: { fr: 'BOFiP — Droit de partage : taux et conditions (BOI-ENR-PTG-10-10)', en: 'BOFiP — Partition duty: rate and conditions (BOI-ENR-PTG-10-10)' } },
  bofipQF: { url: 'https://bofip.impots.gouv.fr/bofip/2494-PGP.html/identifiant=BOI-IR-LIQ-20-20-20-20260407', label: { fr: 'BOFiP — Plafonnement des effets du quotient familial (BOI-IR-LIQ-20-20-20)', en: 'BOFiP — Cap on the tax-share benefit (BOI-IR-LIQ-20-20-20)' } },
  aripa: { url: 'https://www.pension-alimentaire.caf.fr/', label: { fr: 'Aripa (CAF) — Agence de recouvrement et d’intermédiation des pensions alimentaires', en: 'ARIPA (CAF) — child support recovery and payment agency' } },
};
export const srcs = (keys: string[], lang: Locale) => keys.map((k) => { const s = SRC[k] ?? EXTRA[k]; return { name: s.label[lang], url: s.url }; });
